### ISSUE TITLE
When QueueCleaner is disabled, the script is started repeatedly

### ISSUE THREAD

**Issue by Mexx62** [RandomNinjaAtk/arr-scripts#1]
Hi!

Since one of yesterday updates, when the QueueCleaner script is disabled, it is still launched repeatedly (and the `apt install` and `pip install` commands are launched before logging that the script is disabled and exiting, then restarting again...). When comparing to other scripts, it seems that a `sleep infinity` is missing when the script is disabled.
I don't have time to create a PR for it though.

Have a nice day!

**Comment by RandomNinjaAtk** [comment]
Thanks for the info, I'll try to improve it shortly and simply restarting your container should pull the latest version.

**Comment by RandomNinjaAtk** [comment]
It should be fixed, you will need to update your containers to the latest image though...

**Comment by Mexx62** [comment]
I confirm that it is now fixed, thank you! 🙂
As far as I'm concerned, the issue can be closed. Thanks for your prompt response!
