### ISSUE TITLE
[BUG] - Sonarr/Radarr - Recyclarr not working on new installs

### ISSUE THREAD

**Issue by yuquanzzz** [RandomNinjaAtk/arr-scripts#101]
**Application**
Radarr and Sonarr

**Host platform**
Synology, Docker

**Script**
radarr/setup.bash and sonarr/setup.bash

**Script Version**
latest version as of 25 Oct 2023 (no idea what the version is)

**Describe the bug**
Recyclarr service is not being installed to custom-services.d/Recyclarr on Sonarr and Radarr on a new install. Commit 2394b6c and eaa12cc (bug fix for #85) deleted the lines to install the Recyclarr service in radarr/setup.bash and sonarr/setup.bash. After copying the deleted lines to install the Recyclarr service, it works again.

**To Reproduce**
Install it on a new Sonarr and Radarr instance.

**Expected behavior**
Recyclarr should be installed in custom-services.d/ and working.

**Comment by RandomNinjaAtk** [comment]
Good Find, this should be fixed...
