### ISSUE TITLE
Don't want .JPG and .NFO

### ISSUE THREAD

**Issue by xZourSx** [RandomNinjaAtk/arr-scripts#102]
Hello,

I'm looking for a way to avoid getting .jpg and .nfo files

Do you have a solution?

![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/61470872/18977334-83d7-4475-820c-75d799844b9e)

Thank you

**Comment by jaycedk** [comment]
You can disable metadata creation in your arr's
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/17232146/8ea1e0fd-2b12-45ed-bc30-f486ae631876)

**Comment by RandomNinjaAtk** [comment]
> You can disable metadata creation in your arr's ![image](https://user-images.githubusercontent.com/17232146/278794306-8ea1e0fd-2b12-45ed-bc30-f486ae631876.png)

This….
