### ISSUE TITLE
Support Tags for maximumdailyepisodes - sonarr

### ISSUE THREAD

**Issue by RogueGhost93** [RandomNinjaAtk/arr-scripts#105]
I ran into a weird issue where some of my daily shows werent being downloaded due to a search query using DATE format instead of EPISODE format, the only way to fix it was to change the series type STANDARD and add tag DAILY so i can easily distinguish between normal tv shows and my wifes realitytv crap. In order to keep number of her episodes at minimum i  use the maximumdailyepisodes script which doesnt work with tags so i was wondering if there is any way to apply it to tags and not just type of the series. The feature might be useful for some other shows as well that you might wanna keep just last few episodes instead of the whole show. Thanks

**Comment by RandomNinjaAtk** [comment]
This is a neat idea, I can see the use-case. Can you give some example series that I can use for testing purposes... I'm not sure when I'll get to it, but I can look into it.

**Comment by RandomNinjaAtk** [comment]
Spoke too soon earlier, this should now be implemented, check the latest conf file update for the new setting.... It hasn't been tested much. Also if you have some sample series for further testing, that would still be useful...

**Comment by RandomNinjaAtk** [comment]
I'm almost thinking it might be best to have a script that only keeps the latest season... That way you have the full season, regardless of the episode count...

**Comment by RogueGhost93** [comment]
Here is the example The Real Housewives of Atlanta - 2023-09-10 - Reunion Part 1 [WEBDL-1080p], all these crappy housewives shows are going by season numbers and not dates, i have a few more reality shows that are like that but this is a great example because this episodes wasnt found on torrents for past week even though it was available only because of the formating. I have it as a daily show and not standard and thats why PART 2 of houswives reunion was found way before PART 1 which made me investigate in the first place. I get them from EZTV and if you search for part 1 in date format it wont find it, but part 2 will find, and if you switch the show to standard instead of daily it will find both parts right away.

Im gonna go work on the config now since you implemented the feature, thank you so much. Ill post again if there are any issues with it.
