### ISSUE TITLE
[Beets custom plugins] - Lidarr Scripts - Allow custom plugins for beets?

### ISSUE THREAD

**Issue by 7hr08ik** [RandomNinjaAtk/arr-scripts#106]
First of all i want to say a huge thank you for making these scripts. They are amazing and have grown my collection exponentially. Thank you so much

My problem is not with the scripts as such, but more with the tagging of albums. 
What I want is to have my albums tagged with their original release date, and not the specific album release.

E.g.
Offspring - Ignition. The album was originally released 1992. But the edition I have in my library was released 2008. So when I look at Offspring in my library, the albums are all arse about tit. This irks me. I want to have the albums listed as they were originally released, in all of my players and apps.

I have found [beets-oldesdate](https://github.com/kernitus/beets-oldestdate) that would solve my issue. But the scripts, obviously, reset after each reboot/update/shutdown of Lidarr, and thus removing any tweaks I make.

The only alternative I have considered would be to run a separate beets container on my Unraid and have that fire off intermittently. But this is not ideal, and would probably only end up borking everything.

So, would it be possible to add the ability for custom beets plugins in the configs, or an additional config? The plugin i have my eyes on uses a simple 'pip install beets-oldestdate' for installation that could be added to the setup (or and additional setup file?) and the config itself is just an addition set of keys for the config file.

**Comment by RandomNinjaAtk** [comment]
The beets configs are now modifiable, so you can change them to your hearts content... Keep in mind that support will not be provided for modifications.

**Comment by 7hr08ik** [comment]
OMG WOW, that was quick, and straight to the point. Thank you so much
