### ISSUE TITLE
[BUG] - Lidarr - DownloadedAlbumsScan unsuccessful

### ISSUE THREAD

**Issue by JoachimVeulemans** [RandomNinjaAtk/arr-scripts#111]
**Application**
Lidarr

**Host platform**
Synology

**Script**
Audio.service.bash

**Script Version**
2.23

**Describe the bug**
I updated from lidar-extended to arr-scripts but now the albums are not imported into Lidarr.

**To Reproduce**
1. Setup standard Lidarr instance
2. Download album and place it in the /downloads directory.
3. Send a POST request to the Lidarr API to import the album.
4. See that the request is unsuccessful and no log is generated (trace is on)

```
POST http://x.x.x.x:8686/api/v1/command

{
    "name": "DownloadedAlbumsScan",
    "path": "/downloads/complete/Spiritbox-The Fear of Fear-(2023)-MP3-504040121-DEEZER"
}
```

**Expected behavior**
The albums should be imported

**Logs/Screenshots**
No logs are generated concerning the request.

If I change the name of the command or give it an invalid path, the corresponding error logs are generated.

API response (GET):
```
{
    "name": "DownloadedAlbumsScan",
    "commandName": "Downloaded Albums Scan",
    "message": "Completed",
    "body": {
        "path": "/downloads/complete/Spiritbox-The-Fear-of-Fear-(2023)-MP3-504040121-DEEZER",
        "importMode": "auto",
        "requiresDiskAccess": true,
        "isLongRunning": true,
        "sendUpdatesToClient": true,
        "updateScheduledTask": true,
        "completionMessage": "Completed",
        "isExclusive": false,
        "isTypeExclusive": false,
        "name": "DownloadedAlbumsScan",
        "trigger": "manual",
        "suppressMessages": true
    },
    "priority": "normal",
    "status": "completed",
    "result": "unsuccessful",
    "queued": "2023-11-05T17:58:50Z",
    "started": "2023-11-05T17:58:51Z",
    "ended": "2023-11-05T17:58:51Z",
    "duration": "00:00:00.1897285",
    "trigger": "manual",
    "stateChangeTime": "2023-11-05T17:58:51Z",
    "sendUpdatesToClient": true,
    "updateScheduledTask": true,
    "id": 659603
}
```

**Additional context**
I have already created an [issue on the Lidarr repo](https://github.com/Lidarr/Lidarr/issues/4275) since I think the problem is with the application but I did not get a response yet. Could you tell me if I am doing something wrong on that the new version of Lidarr behaves differently? I am 100% sure the Lidarr container can see the directory and files.

**Comment by RandomNinjaAtk** [comment]
I setup a new instance to validate if there was an issue with this: https://github.com/RandomNinjaAtk/arr-scripts/discussions/136

There was no issue, which indicates that nothing is wrong because it's not reproducible. So nothing is to be done here for this request. If you are experiencing and issue, it is likely caused by user-error or some other misconfiguration.... You would need to review your app logs further, possibly increase the logging level to debug it....
