### ISSUE TITLE
[BUG] - Lidarr - Media Management Name Scheme resets after server/system reboot

### ISSUE THREAD

**Issue by Deathbot64** [RandomNinjaAtk/arr-scripts#116]
**Application**
Lidarr

**Host platform**
Windows/Dockers

**Script**
Lidarr

**Script Version**
Latest

**Describe the bug**
Every Time I do a reboot my system the naming scheme resets itself. If I just restart Lidarr the naming scheme wont change.

Defaults back to {Artist CleanName} - {Album Type} - {Release Year} - {Album CleanTitle}{ (Album Disambiguation)}/{medium:00}{track:00} - {Track CleanTitle}

**To Reproduce**
1. Setup your naming scheme
2. Restart system
3. After system loads naming scheme is defaulted back to what is was before

**Expected behavior**
I should not need to rename

**Comment by RandomNinjaAtk** [comment]
Either disable autoconfig or the individual option....

See: https://github.com/RandomNinjaAtk/arr-scripts/blob/2474af817e83932efc0304371211957b8fbfaf7a/lidarr/extended.conf#L28

**Comment by Deathbot64** [comment]
Thank you so much. Should have realized that myself. Sorry to waste your time.
