### ISSUE TITLE
Request to add streamrip

### ISSUE THREAD

**Issue by espentruls** [RandomNinjaAtk/arr-scripts#12]
Feature request to add [streamrip](https://github.com/nathom/streamrip/tree/dev) as a download option, or maybe replace the existing solutions. 
I've started the initial setup over on my fork on the lidarr-streamrip branch

**Comment by RandomNinjaAtk** [comment]
If you can get it working and verify it works with both tidal/deezer, I'd gladly accept a PR for it. Should still keep fryer because it requires no account...

**Comment by RandomNinjaAtk** [comment]
I think I had messed with that app in the past and there was probably a reason at that time as to why I didn't use it. I think it was due to technical issues with the app itself not working.

But it may have improved since then....

Obviously a single client vs supporting multiple clients would make it easier to support but that's only if it works.

**Comment by RandomNinjaAtk** [comment]
Thinking about it some more, I don't think it supports lyrics or didn't at the time, which also made it a no-go for me personally.

**Comment by RandomNinjaAtk** [comment]
This is not needed, closing...

**Comment by TheRealGramdalf** [comment]
> Should still keep fryer because it requires no account...
streamrip doesn't need an account for deezer, but it doesn't support direct apple music/spotify download - rather it matches the isrc on another platform, somewhat similar to what freyr does in some cases.

> Tidal specifically was the issue I believe because that was the time when I looked at integrating it... if I'm remembering correctly...

I can't verify for certain, but Tidal is supported, granted you have a login/ARL. What you may be thinking of is Spotify/apple music - it doesn't support downloading directly from spotify, but I'm not sure if freyr is much different (when no account is given) - I think it just takes in a spotify/apple music playlist and finds the relevant song on YT music to download (which isn't always correct). 

> This is not needed, closing...

I would argue that streamrip is good for getting direct lossless rips with a premium account, and freyr is good as a fallback/when quality isn't a worry. Streamrip integration would be very nice, especially with the [upcoming v2.0](https://github.com/users/nathom/projects/1/views/1)

**Comment by RandomNinjaAtk** [comment]
@TheRealGramdalf I’ll gladly review a PR…. Otherwise, if it ain’t broke, don’t fix it….
