### ISSUE TITLE
Loss of Radarr settings

### ISSUE THREAD

**Issue by xZourSx** [RandomNinjaAtk/arr-scripts#123]
Before using the arr-script, I had configured radarr optimally.
I use radarr on a docker within Synology.

Since I installed the script, after a reboot of the container I've lost several parameters: 

Standard Movie Format :
Before : 
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/61470872/1c3eaa01-4cbb-4699-a7d0-0400d8060e66)

After : 
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/61470872/43aa5de4-512c-4ec8-95f5-65d0a0146ae2)

Before : 
It was disabled 
After : 
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/61470872/36cdb50e-8f89-4b73-a3f9-29642d46afec)

Thank you for your help,

**Comment by RandomNinjaAtk** [comment]
Use the config file to turn off the features you don't want... This is all in the autoconfig script... Or disable the autoconfig script.

Keep in mind, the autoconfig is pretty well designed to follow best practices....  This is not a bug or an issue, please read the config and turn off things you don't want it to do....

Links:
https://github.com/RandomNinjaAtk/arr-scripts/blob/main/radarr/extended.conf

https://github.com/RandomNinjaAtk/arr-scripts/blob/524b51ee598352ab8f060e532f818f09c92f78d2/radarr/extended.conf#L4

https://github.com/RandomNinjaAtk/arr-scripts/blob/524b51ee598352ab8f060e532f818f09c92f78d2/radarr/extended.conf#L18C1-L23
