### ISSUE TITLE
[FEATURE] - Lidarr - Manually invoke download

### ISSUE THREAD

**Issue by piscopoc** [RandomNinjaAtk/arr-scripts#126]
This is really great work! Quick question, Is there a way to manually call the scripts to download an album through Deezer or Tidal? Depending on the album the search is sometimes hit or miss and it would be great to just feed an album id via the command line to kick off the whole process.

**Comment by RandomNinjaAtk** [comment]
You can just do that through the CLI if you want, you should disable the script from running automatically if you want to do that...

**Comment by piscopoc** [comment]
Perfect thanks for the fast response. Any hints on what that command looks like?

**Comment by RandomNinjaAtk** [comment]
https://github.com/RandomNinjaAtk/arr-scripts/blob/425c59e06c17fe006bbfc26cb4ef68c69249fc43/lidarr/Audio.service.bash#L456
