### ISSUE TITLE
[FEATURE] - Lidarr - Deezer ARL Check and Update

### ISSUE THREAD

**Issue by hockeygoalie35** [RandomNinjaAtk/arr-scripts#133]
**Is your feature request related to a problem? Please describe.**
If you're not using your own Deezer ARL token, they expire often. There's no way to know if the ARL token is expired, except you realize that you haven't been grabbing new releases for a while. Also as a consequence once you change the token, you need to clear out the 'notfound' folder, or it will be 90 days (by default) before it tires missed releases again.

**Describe the solution you'd like**
An ARL Checker python script exists by attempting to login: https://rentry.co/stracc
I've taken the relevant class from this script and wrote a new class that extracts the current token out of extended.conf and runs it through this Deezer login class. It would be cool the run the check every day or so, using a bash script to sleep or a chronjob so python isn't running the whole time. Would it be possible to warn the user through Lidarr, or would that require modifications the image? 

My script also has a second function to set a new token to extended.conf. This could be used to quickly update the token rather than doing it manually. It also deletes the "notfound" logs to retry any missed releases to bypass the default wait time of 90 days.

**Additional context**
Current output of my script. Not shown, if the token is valid, it exits with one code, and if not, with another. This can be captured by your scripts and do anything further if needed.

![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/7758029/26549ba0-be99-41d0-8af0-ab71b9335659)

My main purpose of opening this issue is to see if you were open to adding a Python script to your project. If so, I'll create a Pull Request.

**Comment by RandomNinjaAtk** [comment]
PR welcome

**Comment by Coder84619** [comment]
This would be awesome.

**Comment by hockeygoalie35** [comment]
@Coder84619  I got it working, and a little Telegram bot to notify you if it expires. Just need to work the bugs out and pack it up in my forked Repo. So soonish!

**Comment by Coder84619** [comment]
@hockeygoalie35 That's awesome! Looking forward to such a great community enhancement.

**Comment by hockeygoalie35** [comment]
@RandomNinjaAtk , I noticed in setup.bash, there's a pip install with a bunch of packages. One of them is requests, which my script happens to use. when I run a pip list command, It shows that requests never gets installed.

From the startup:
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/7758029/28767111-6fdc-44bd-ad56-ebb3597344a7)

And "pip list" output after the fact:

![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/7758029/4f2b58be-bef6-436a-b4d7-d0650c907811)


Any ideas?

**Comment by RandomNinjaAtk** [comment]
I get a lot more pip packages in my list, and it includes requests.... So yours is not showing most of the installed packages such as beets.....

So your either running the command in the wrong place or doing something else wrong in your particular setup because its not reproducible. Make sure you followed the procedure in the readme for the correct installation procedures...

**Comment by hockeygoalie35** [comment]
Installation was as Readme states. Digging further...Beets is has jellyfish as a dependency, which fails due to trying to compile from a source written in Rust, which fails the pip operation.

```
Collecting jellyfish
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... error
error: subprocess-exited-with-error
  
× Preparing metadata (pyproject.toml) did not run successfully.
      
Cargo, the Rust package manager, is not installed or is not on PATH.
This package requires Rust and Cargo to compile extensions. Install it through
the system's package manager or via https://rustup.rs/
      
Checking for Rust toolchain....
[end of output]
```


Strangely, on my host system, it installs Jellyfish just fine, using wheel:
`jellyfish-1.0.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl`

However in the docker container I get a pip error:

`ERROR: jellyfish-1.0.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl is not a supported wheel on this platform.`

Manually installing Jellyfish==0.10, and then restarting the container, allowed everything to install correctly.

Once installed, setup.bash can run correctly and install everything as normal. Looks like I have something to take up with Jellyfish's repo.
