### ISSUE TITLE
[FEATURE] - Lidarr - Add related artists unmonitored

### ISSUE THREAD

**Issue by wjbeckett** [RandomNinjaAtk/arr-scripts#139]
**Is your feature request related to a problem? Please describe.**
When adding related artists via the automated script, I'd like to be able to set them to unmonitored so that I can manually decide if I want to add the artist.

**Describe the solution you'd like**
When the related artists portion of the script runs to add related artists to Lidarr, I'd like to be able to add them in an unmonitored state or at least be able to choose if they should be added monitored or unmonitored. Having a configuration item for "AddRealtedArtistMonitored" would be the idea way to do this so we have the choice to add the artist monitored or not.

**Describe alternatives you've considered**
Configuring Lidarr to add new artists as unmonitored doesn't seem to work via the script.

**Comment by RandomNinjaAtk** [comment]
@wjbeckett 
Update your config, make the settings change and verify everything is working. I have not tested the changes but it should work...
