### ISSUE TITLE
Lidarr Autoconfig

### ISSUE THREAD

**Issue by jaycedk** [RandomNinjaAtk/arr-scripts#14]
Hi and thank you for continuing this project 😄 

I do have a minor issue.
For some reason i can not turn off autoconfig in Lidarr.
I have tried to go from "true" to "false" and restartet lidarr a copple of times.
My manuel changes are revertet back to Autoconfig standard.

##### SCRIPT ENABLEMENT
enableAutoConfig="false" # true = enabled :: Automatically configures Lidarr with optimal settings
enableAudio="true" # true = enabled :: Enables the Audio script to run automatically
enableVideo="true" # true = enabled :: Enables the Video script to run automatically
enableQueueCleaner="true"  # true = enabled :: Enables the QueueCleaner script to run automatically

**Comment by RandomNinjaAtk** [comment]
Update to the latest and it should now be resolved.

**Comment by jaycedk** [comment]
Nice 😄  will test in 15 min.

**Comment by jaycedk** [comment]
That did it.
Thank you so very much 🥇
