### ISSUE TITLE
[BUG] - Lidarr - Beets tagging breaks albumtype metadata tag

### ISSUE THREAD

**Issue by cherryontopknife** [RandomNinjaAtk/arr-scripts#141]
**Application**
Lidarr

**Host platform**
Unraid

**Script**
Unsure where exactly the issue is. Beets tagger?

**Describe the bug**
[This issue has been documented before.](https://github.com/beetbox/beets/issues/4528)

I didn't change anything in my setup, other than update containers.

**Comment by RandomNinjaAtk** [comment]
Sounds like a beets problem… if there is something that can be done on this side to solve it, I’ll look into it but the script just hands it off to beets… so it’s outside of scope of support for this repo…

**Comment by cherryontopknife** [comment]
I understand. In the future, is there an alternative way to bring attention to third party issues you don't directly control?

By the way, to fix this, I just turned off beets tagging in the extended.conf file. Now releases are being properly tagged, and showing up in the expected grouping.

**Comment by RandomNinjaAtk** [comment]
#170 #182
