### ISSUE TITLE
[BUG] - Sonarr - update to 4.0.0.746 broke something

### ISSUE THREAD

**Issue by jaycedk** [RandomNinjaAtk/arr-scripts#145]
**Application**
Sonarr v.4.0.0.746
lscr.io/linuxserver/sonarr:develop

**Host platform**
Unraid 6.12.6

**Script**
I think its the functions script that not working any more, after the update.

**Script Version**
Newly updated Wednesday, I updated all your scripts, and extended.conf.
And that was working till I updated this morning.

**Describe the bug**
Errors in docker logs

**To Reproduce**
Update lscr.io/linuxserver/sonarr:develop

**Logs/Screenshots**
[Sonarr_log.txt](https://github.com/RandomNinjaAtk/arr-scripts/files/13801207/Sonarr_log.txt)
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/17232146/e15a1795-c423-4926-8ba8-72ead445c709)

**Comment by jaycedk** [comment]
Guess it could be something to do with this.
Ohh well I'm not i a rush 😉
Happy New years 🎉🎇🎆
# Sonarr v4 Released

After a year of development and almost 1000 commits by more than 100 contributors Sonarr v4 is officially launched and out of beta. There are hundreds of changes to both the UI and the backend, and as such an upgrade is not backwards compatible.

**The major changes include:**

* Upgrade to .NET 6 - this removes the mono dependancy and brings a nice speed upgrade
* Custom Formats replace the old Preferred Words - Gain much more control over the releases Sonarr chooses. Note that the migration here is tricky and you will need to rework the migrated custom formats
* ffprobe has replaced MediaInfo - no more crashes from failed media scans
* Dark Mode!
* Automated API documenation (found at https://sonarr.tv/docs/api/)
* Language profiles removed and integrated into Custom Formats - guidance on how to implement them can be found at https://trash-guides.info/Sonarr/Tips/How-to-setup-language-custom-formats/
* Authentication is required by default - prevent unauthorized users from accessing your Sonarr instance
* Mass Editor has moved to the standard Series Overview page (use the select series button)
* UI langauge is selectable and translatable - contributions can be made at [https://translate.servarr.com](https://translate.servarr.com/)
* Notifications - support additional providers and new notification triggers
* Import Lists - support for additional providers
* Auto Tagging - let Sonarr tag your shows based on several conditions
* Quality Size Preference - additon of preferred size option (on top of the min and max size settings)
* Additional montitoring options - choose how Sonarr monitors future seasons
* Override and Grab - tell Sonarr what you're manually grabbing if it parses incorrectly
* Test parsing popup in the UI
* v2 API endpoint has been removed
* Hundreds of release parsing improvements
* and much more...

**How To Upgrade**

V4 has now been pushed to the main branch. Updates will happen differently depending on how you have Sonarr installed on your system.

* Docker container providers will update their `:latest` tag to v4
* Native versions for Windows, MacOS and Linux have been published and are available to download from [sonarr.tv](https://sonarr.tv/#download). They will need to be downloaded and installed manually, updates will not happen via Sonarr. Note that x86 releases are no longer available for Linux.
* When upgrading a linux install, you will need to update your sonarr.service file so that the `ExecStart` line no longer references mono. an example of how it may look can be found here: https://github.com/Sonarr/Sonarr/blob/develop/distribution/debian/sonarr.service

Make sure to make a backup in v3 first before upgrading to v4 incase anything goes wrong and you need to roll back.

**Issues when upgrading**

If you had a lot of preferred words in Sonarr v3 then you will see many migrated custom formats in v4. These will need to be edited or deleted and readded. The `{Preferred Words}` naming token is also replaced with the `{Custom Formats}` token. Check your naming strings.

Due to multiple database migrations we've seen that some corrupt databases that were doing OK in v3 have broken in v4. You can try to follow our corrupt database repair guide https://wiki.servarr.com/useful-tools#recovering-a-corrupt-db or reach out to one of our Support channels.

Due to the move from mono to .NET 6 there may be some small changes required to your Reverse Proxy: https://wiki.servarr.com/sonarr/faq-v4#my-reverse-proxy-doesnt-work-anymore

**Moving from Develop to Main**

Now that v4 has released, the develop and main branches are currently equal. On systems that support automatic updates through Sonarr you should be redirected back to `main` automatically. Otherwise please update you branch and updates as necessary if you'd like to return to `main` releases.

Users that wish to stay on `develop` will need to manually change their branch after updating to at least 4.0.0.741.

**Comment by justinglock40** [comment]
I got the same issue recently. was working fine up until last night looks like

**Comment by justinglock40** [comment]
With this python error as well.

![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/23133649/86b79d03-3d14-4c3b-9fb9-b917c590a9d3)

**Comment by justinglock40** [comment]
Going back to this tag does not cause this breaking change with python: linuxserver/sonarr:develop-4.0.0.740-ls18

**Comment by RandomNinjaAtk** [comment]
Also seeing the error, not sure yet what the fix is... But I'll look into it...

**Comment by RandomNinjaAtk** [comment]
Honestly, the change I just pushed fixes it... However, I'm not sure if they're are any unintended consequences with the change... Restart the container to pull the latest setup script....

**Comment by jaycedk** [comment]
Second run all good 😎
Thank you for fixing this 👍

@justinglock40  Is it fixed on you your end too ?

**Comment by justinglock40** [comment]
> Second run all good 😎
> 
> Thank you for fixing this 👍
> 
> 
> 
> @justinglock40  Is it fixed on you your end too ?

Yes. Seems to be in working order now. Thanks! RandomNinjaAtk
