### ISSUE TITLE
[BUG] - SONARR - DailySeriesTrimmer unmonitoring but not deleting

### ISSUE THREAD

**Issue by craigjmidwinter** [RandomNinjaAtk/arr-scripts#153]
**Application**
Sonarr

**Host platform**
Docker

**Script**
DailySeriesTrimmer

**Script Version**
1.2

**Describe the bug**
The daily series trimmer seems to be unmonitoring series as expected, but not deleting files

**To Reproduce**
1. Setup a daily series
2. Download episodes beyond limit set for daily series
3. Check series
4. Episodes are unmonitored but files still exist

**Expected behavior**
Files for unmonitored daily episodes should be deleted

**Logs/Screenshots**
[DailySeriesEpisodeTrimmer-2023_11_07_02_43_AM.txt](https://github.com/RandomNinjaAtk/arr-scripts/files/13851522/DailySeriesEpisodeTrimmer-2023_11_07_02_43_AM.txt)

**Additional context**
Manually deleting files via the Sonarr UI works as expected leading me to believe it's not a permissions issue

**Comment by RandomNinjaAtk** [comment]
Your not on the lastest version of scripts. Update and see if that resolves it.

**Comment by craigjmidwinter** [comment]
Sorry, needed to restart a second time. The issue still occurs on 1.5 
[SeriesEpisodeTrimmer-2024_01_06_09_54_PM.txt](https://github.com/RandomNinjaAtk/arr-scripts/files/13852159/SeriesEpisodeTrimmer-2024_01_06_09_54_PM.txt)

**Comment by RandomNinjaAtk** [comment]
FYI: I'm unable to replicate the issue, so the problem is somewhere with your particular configuration.

**Comment by ryansonshine** [comment]
I'm also having this issue. Using the latest version of the script as well.

```
2024-01-06 21:54:37 :: SeriesEpisodeTrimmer :: 1.5 :: Jeopardy! (ID:) :: SE :: :: Unmonitored Episode ID :: 27831
2024-01-06 21:54:37 :: SeriesEpisodeTrimmer :: 1.5 :: Jeopardy! (ID:) :: SE :: :: Deleted File ID ::
```

The file ID is supposed to be logged on the second line but it's not.
