### ISSUE TITLE
[BUG] - Lidarr - Deezer truncates long album titles

### ISSUE THREAD

**Issue by Bassetts** [RandomNinjaAtk/arr-scripts#156]
**Application**
Lidarr

**Host platform**
Ubuntu 22.04.1

**Script**
Audio.service.bash

**Script Version**
2.24

**Describe the bug**
It seems that Deezer truncates album titles to a maximum of 130 characters. I can't find any documentation of this and have only found it through trial and error. This means that if you have an album with a title longer than this then both the artist album search and fuzzy search will fail to find a result.

I have managed to work around this [with a fairly quick hack](https://github.com/Bassetts/arr-scripts/commit/96218b939ad34a9717dbb2fc4ff724dddd9e1976) which truncates the album title to 130 characters before cleaning it. This means a result is found when doing the artist album search.

Note: the album downloaded after my quick and dirty hack but I got a `System.IO.PathTooLongException: The specified file name or path is too long, or a component of the specified path is too long.` exception when trying to import the tracks. I am not sure if this is another bug.

[MusicBrainz entry for the album](https://musicbrainz.org/release-group/b7493310-d408-44e2-a2d6-bbbd485d7abc)
[Deezer link for the album](https://www.deezer.com/en/album/124296892)

**To Reproduce**
1. Monitor an album that is on Deezer with a title longer than 130 characters
2. Audio script will run and not find a result from Deezer

**Expected behavior**
The album is found and downloaded

**Logs/Screenshots**
```
lidarr  | 2024-01-09T13:52:06.388996714Z 2024-01-09 13:52:06 :: Audio :: 2.24 :: 1 :: missing :: 1 of 1 :: Bring Me the Horizon :: Music to listen to~dance to~blaze to~pray to~feed to~sleep to~talk to~grind to~trip to~breathe to~help to~hurt to~scroll to~roll to~love to~hate to~learn Too~plot to~play to~be to~feel to~breed to~sweat to~dream to~hide to~live to~die to~GO TO :: EP :: Artist Search :: Deezer :: Explicit :: Music to listen to~dance to~blaze to~pray to~feed to~sleep to~talk to~grind to~trip to~breathe to~help to~hurt to~scroll to~roll to~love to~hate to~learn Too~plot to~play to~be to~feel to~breed to~sweat to~dream to~hide to~live to~die to~GO TO :: MusictolistentodancetoblazetopraytofeedtosleeptotalktogrindtotriptobreathetohelptohurttoscrolltorolltolovetohatetolearnTooplottoplaytobetofeeltobreedtosweattodreamtohidetolivetodietoGOTO vs Musictolistentodancetoblazetopraytofeedtosleeptotalktogrindtotriptobreathetohelptohurttoscrolltorollt :: Not a match...
```

**Comment by RandomNinjaAtk** [comment]
I welcome a PR for the change. Sound like we may just need to truncate the album folder name. If I had to guess, because the folder name is the entire album name, its too long for lidarr to handle, hence the system io error.

If you end up writing a PR, please also apply it to Tidal, because I'm sure it's also affected by this issue.

**Comment by Bassetts** [comment]
> I welcome a PR for the change. Sounds like we may just need to truncate the album folder name. If I had to guess, because the folder name is the entire album name, its too long for lidarr to handle, hence the system io error.
> 
> If you end up writing a PR, please also apply it to Tidal, because I'm sure it's also affected by this issue.

I think there are probably two PRs here. One to fix the issue with Deezer truncating the album title so the search fails, and another to fix the filename path being too long.

I am happy to work on both of those when I get some time. My bash isn't great so it would be good to get some practice in 😄

**Comment by RandomNinjaAtk** [comment]
@Bassetts  
The changes I just pushed may solve it... I based the changes on what I saw in your fork... However, I have not fully tested these changes... It should work....
