### ISSUE TITLE
Add a songs mode - Lidarr 

### ISSUE THREAD

**Issue by chicco-carone** [RandomNinjaAtk/arr-scripts#157]
**Is your feature request related to a problem? Please describe.**
I just started using lidarr with a headphones subscription and i wanted to download all the music in my playlist with it but after connecting my spotify playlist it wanted to download 60K tracks and my playlist is only 600. 
**Describe the solution you'd like**
There are multilple issues on the lidarr repo mentioning the ability to download singular songs which could be achieved by only downloading the single song but if it isn't possible it could download the whole album and delete the not wanted tracks.

**Describe alternatives you've considered**
No alternative for now except doing the downloading and deleting manually

**Comment by RandomNinjaAtk** [comment]
Lidarr is an album based application. These tools are to be used with the main app. If that is something you want, you’ll need to add the capability to Lidarr itself or write your own tool.
