### ISSUE TITLE
[BUG] - lidarr - [ERR] Login failed.Device authorization failed. Please choose another apikey.

### ISSUE THREAD

**Issue by TheUltimateC0der** [RandomNinjaAtk/arr-scripts#16]
**Application**
Lidarr

**Script**
Audio

**Script Version**
Unknown

**Describe the bug**
When tidal-dl is executed inside the container, it should normally (i guess) show the URL to authotize it. Instead is shows the error mentioned in the title. tidal-dl seems to expect the `tidal-dl.json` at `/config/.config/tidal-dj.json`. 

Your script places the file in `/config/tidal-dl.json`

**To Reproduce**
1. Install from scratch
2. follow your own lidarr installation guide
3. add artist
4. restart container
5. see mentioned logs
6. create `.config` dir in `/config`
7. copy over `tidal-dl.json` from `/config/extended/tidal-dl.json` to `/config/.config/tidal-dj.json`
8. problem solved

**Expected behavior**
Either tell tidal-dl where to find the config, or let your script move it to `/config/.config/tidal-dj.json`

**Comment by RandomNinjaAtk** [comment]
Please include log data from the Audio script so the version can be validated.

**Comment by TheUltimateC0der** [comment]
Where can I see the version ?

**Comment by RandomNinjaAtk** [comment]
Its in the log data for the script, log data is also needed to demonstrate/show the failure.

**Comment by TheUltimateC0der** [comment]
I literally installed it like an hour ago, and filled out steps to completely reproduce the issue. I dont think lidarr or any other logs would help much more to reproduce the problem.

**Comment by RandomNinjaAtk** [comment]
@TheUltimateC0der So what was the problem?

**Comment by TheUltimateC0der** [comment]
Idk... What problem ?

**Comment by RandomNinjaAtk** [comment]
So it just started working?

**Comment by TheUltimateC0der** [comment]
Nope. But I know how to fix things myself. This was just so you can fix it for everyone else. If you dont, I dont care ¯\_(ツ)_/¯

**Comment by RandomNinjaAtk** [comment]
I care, but when a user refuses to produce requested information, such as logs, which is not an unreasonable ask for troubleshooting purposes, why should I spend my time... just sayin...

**Comment by TheUltimateC0der** [comment]
> I literally installed it like an hour ago, and filled out steps to completely reproduce the issue. I dont think lidarr or any other logs would help much more to reproduce the problem.

As stated above. Nothing more to say.
