### ISSUE TITLE
[BUG] - SONARR- YoutubeSeriesDownloader showing "ERROR :: No Download URL found, skipping"

### ISSUE THREAD

**Issue by maxi1134** [RandomNinjaAtk/arr-scripts#162]
**Application**
Sonarr

**Host platform**
Proxmox

**Script**
 YoutubeSeriesDownloader
**Script Version**
[Where can I find this? I believe I have the last one]

**Describe the bug**
YoutubeSeriesDownloader says there is no YouTube video for an "episode" even though I went and added the ID to theTVDB database. 
I am wondering if there is any cache I need to empty for the script to grab the new data. It appears my update was accepted on theTVDB 

**To Reproduce**
Start the Sonarr docker after updating TheTVDB.

**Expected behavior**
The script downloads the video.

**Logs/Screenshots**

2024-01-12 20:47:01 :: YoutubeSeriesDownloader :: 2.0 :: 4/12 :: 1/136 :: Technology Connections :: S2015E1 :: ERROR :: No Download URL found, skipping

**Additional context**
https://thetvdb.com/series/technology-connections/episodes/7695900

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by RandomNinjaAtk** [comment]
Might just take time... as you said, possibly a caching issue of some sort.

**Comment by RandomNinjaAtk** [comment]
So I just tested that series you linked and the episode worked… so my guess it was a caching issue and should self resolve… So not a bug…

**Comment by maxi1134** [comment]
> So I just tested that series you linked and the episode worked… so my guess it was a caching issue and should self resolve… So not a bug…



Same results here!


As mentioned initially "I am wondering if there is any cache I need to empty for the script to grab the new data. It appears my update was accepted on theTVDB" The cache part was part of the question.

**Comment by githubusr80** [comment]
No, there isn’t anything to do on the script end

**Comment by RandomNinjaAtk** [comment]
No, I don’t think anything cab be done on the script/user’s end.
