### ISSUE TITLE
[BUG] - Lidarr - Audio script freezes on certain albums/songs

### ISSUE THREAD

**Issue by Flapperoo** [RandomNinjaAtk/arr-scripts#164]
**Application**
Lidarr

**Host platform**
Unraid Docker
**Script**
Audio

**Script Version**
2.30

**Describe the bug**
Audio script freezes at certain tracks from certain albums at the embedding metadata stage. 

**To Reproduce**
1. Have an affected album as monitored (in my case Kendrick Lamar - To Pimp A Butterfly)
2. Let script run and do it's thing
3. Script freezes at embedding metadata on affected song (in this case Track 15. I )

**Expected behavior**
Script proceeds and imports the album.

**Logs/Screenshots**
[Audio-2024_01_16_10_53_PM.txt](https://github.com/RandomNinjaAtk/arr-scripts/files/13952105/Audio-2024_01_16_10_53_PM.txt)

**Additional context**
Script freezes consistently on a song on different albums, most albums are fine, this only happens to a few albums.
Stock configuration both from the Lidarr script and Lidarr config.

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by RandomNinjaAtk** [comment]
This is a problem with the download client…. Nothing to do here… you can open an issue on the download clients GitHub repo to see if they can fix it…. 

The only thing that might be possible would be a workaround that kills the client after a certain period of time… but that doesn’t fix the problem….

**Comment by Flapperoo** [comment]
Just to add more context here, Freyr works and finishes normally, tested within the same lidarr container using the same commands from the script.
```
freyr --no-bar --no-net-check -d config/extended/downloads/audio/incomplete deezer:album:9896728
```
So I'm not exactly sure where the fault is.
