### ISSUE TITLE
[BUG] - lidarr - scripts dont work with port 8688

### ISSUE THREAD

**Issue by Xtreme010** [RandomNinjaAtk/arr-scripts#168]
**Application**
Lidarr

**Host platform**
Synology with docker container

**Script**
All of them

**Script Version**
Latest

**Describe the bug**
I have a lidarr docker container which works on port 8688. It seems to function fine other than the ninja script doesn't work. Once the container is running the UI is accessible however in the logs I just get lidarr not ready waiting and that's all it does. Just filling up the logs.

**To Reproduce**
1. Create docker container and change port to 8688
2. Run instance
3. Check log files

**Expected behavior**
I would expect the instance to run the scripts and not report that lidarr is not ready when infact it is.

**Logs/Screenshots**
I can supply of this will help?

**Additional context**
Everything works fine if I run the container on port 8686 but unfortunately I can't run it on this port as there is already another app using the port.

**Comment by RandomNinjaAtk** [comment]
https://github.com/RandomNinjaAtk/arr-scripts/issues/31

**Comment by RandomNinjaAtk** [comment]
The linked issue should solve your problem.
