### ISSUE TITLE
[FEATURE] - SabNZBd - Audio tar archive extraction before audio file validation

### ISSUE THREAD

**Issue by ChuckFindlay** [RandomNinjaAtk/arr-scripts#169]
**Is your feature request related to a problem? Please describe.**
I have found some sources are TAR archiving audio files which make the "clean()" function fail in the audio.bash script.

**Describe the solution you'd like**
I have created a workaround for this and thought others may benefit:

Original "audio.bash" script "clean () function:

```
        clean () {
                if [ $(find "$1" -type f -regex ".*/.*\.\(flac\|mp3\|m4a\|alac\|ogg\|opus\)" | wc -l) -gt 0 ]; then
                        find "$1" -type f -not -regex ".*/.*\.\(flac\|mp3\|m4a\|alac\|ogg\|opus\)" -delete
        ...
```

Added additional if statement to cater for tar archives

```
        clean () {
                # UnTAR tarballs if they exist
                if [ $(find "$1"/ -name "*.tar" | wc -l) -gt 0 ]; then
                        log "TARBALL Found, Un-taring..."
                        for fname in "$1"/*.tar; do
                                tar x -f "$fname" -C "$1"
                        done
                fi
                if [ $(find "$1" -type f -regex ".*/.*\.\(flac\|mp3\|m4a\|alac\|ogg\|opus\)" | wc -l) -gt 0 ]; then
                        find "$1" -type f -not -regex ".*/.*\.\(flac\|mp3\|m4a\|alac\|ogg\|opus\)" -delete
        ...
```

**Comment by RandomNinjaAtk** [comment]
Shouldn’t Sab be in archiving these files before the script runs? At least that’s what happens in my usage… sounds like you need to adjust your sabnzbd configuration to recursively unpack

**Comment by RandomNinjaAtk** [comment]
Nothing to do here, believe this is user-error....
