### ISSUE TITLE
Arr app not detected

### ISSUE THREAD

**Issue by VPsych** [RandomNinjaAtk/arr-scripts#17]
Hello, I'm having difficulty getting the script to work. Following the directions I've created mounts for the `/custom-services.d` and `/custom-cont-init.d` folders. And placed the .bash script into the `/custom-cont-init.d` folder. However, monitoring the logs on the container start-up never indicated anything was found in custom-cont-init-d and no changes were observed in the folder01 folder. After going into the docker container's instance and manually executing the bash script it downloaded the dependencies and script files. However, now QueueCleaner reports it doesn't see my Arr app instance. 

I saw that it [doesn't handle custom lidarr names ](https://github.com/RandomNinjaAtk/arr-scripts/issues/2)so I tried changing the name from lowercase lidarr to Lidarr. But that doesn't make a difference. 

My Docker Config
```
docker run
  -d
  --name='lidarr'
  --net='proxynet'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Server"
  -e HOST_CONTAINERNAME="lidarr"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8686]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lidarr.png'
  -p '8686:8686/tcp'
  -v '/mnt/user/T_Media/Torrent/downloads/':'/downloads':'rw'
  -v '/mnt/user/media/music/':'/music':'rw'
  -v '/mnt/user/downloads/amd/':'/downloads-amd/':'rw'
  -v '/mnt/user/appdata/lidarr/scripts/folder01/':'/custom-services.d':'rw'
  -v '/mnt/user/appdata/lidarr/scripts/folder02/':'/custom-cont-init.d ':'rw'
  -v '/mnt/user/media/videos/music-videos/':'/music-videos':'rw'
  -v '/mnt/user/downloads/lidarr-extended/':'/amddownloads/':'rw'
  -v '/mnt/user/appdata/lidarr':'/config':'rw'
  --log-opt max-size=50m
  --log-opt max-file=1 'linuxserver/lidarr' 
```

Error Log
```
07/14/2023 2:57:13 PM ./run: line 118: PackageInstallation: command not found
07/14/2023 2:57:13 PM ./run: line 120: xq: command not found
07/14/2023 2:57:13 PM 2023-07-14 14:57:13 :: QueueCleaner :: 1.0.6 :: ERROR :: Arr app not detected, exiting...
```

**Comment by RandomNinjaAtk** [comment]
The name matters in the web application settings. Not for the docker-run or compose name. Check your Lidarr Web Interface and make sure the name is "Lidarr"

**Comment by RandomNinjaAtk** [comment]
I have an idea on how to improve/fix it though. The port should never change, so I could go by the port instead of app name... I'll look into making that change. But in the meantime, you can just change the name...

**Comment by VPsych** [comment]
Thanks for the clarification. The instance name is “ Lidarr”. So I don’t think the name issue is related. On Jul 14, 2023, at 15:14, RandomNinjaAtk ***@***.***> wrote:﻿
The name matters in the web application settings. Not for the docker-run or compose name. Check your Lidarr Web Interface and make sure the name is "Lidarr"

**Comment by RandomNinjaAtk** [comment]
Follow the instructions for setup/installation and updating: https://github.com/RandomNinjaAtk/arr-scripts/blob/main/lidarr/readme.md

The change that was implemented should fix the name issue, however after reading your log a bit more, it looks like the installation failed in some shape or form. Which might be related to your personal env, most likely a networking issue. 

Make sure the script version matches to ensure you updated....
