### ISSUE TITLE
[BUG] - LIDARR - Stopped working for aarch64

### ISSUE THREAD

**Issue by RandomUser345** [RandomNinjaAtk/arr-scripts#172]
**Application**
Lidarr

**Host platform**
RaspberryPi aarch64 with Ubuntu 22.04

**Script**
Audio

**Script Version**
2.30

**Describe the bug**
There are currently issues with the aarch64 version of Lidarr and those scripts. I've pinpointed this down to jq and cargo/rust.
1) jq is having an issue extracting data from the config.xml: throwing an error on aarch64, works on other platforms
2) cargo/rust is missing from the lidarr image

To "fix" this you can add cargo and rust in a forked version of the setup AND you need to specify following variables in the extended.conf so it will not try to read it from the config.xml:
arrUrl="http://127.0.0.1:8686"
arrApiKey="xxx"
arrName="Lidarr"
arrPort="8686"

I know this is not in your focus and I won't expect anything from your side, but this is for reference if someone else has this issue.

**To Reproduce**
Start...

**Comment by RandomNinjaAtk** [comment]
I only support x86_64. It's possible that dependencies are missing for ARM based systems. I'll gladly review a PR for possible changes to fix it, but I won't be supporting it...

**Comment by RandomUser345** [comment]
Yeah, I know you only support x86_64: I made it work on my ARM machine (already described in the initial request) but I'm afraid I'll break it for everyone else: at least blow up the image a few hundred MB's.

**Comment by RandomNinjaAtk** [comment]
Thanks for posting the issue to notify others

**Comment by nothing2obvi** [comment]
Thank you for this. It fixed my issue.
