### ISSUE TITLE
[BUG] - Lidarr - Artist Folder Format changes aren't reflected in Library album rename preview

### ISSUE THREAD

**Issue by Coder84619** [RandomNinjaAtk/arr-scripts#178]
**Application**
Lidarr

**Host platform**
Linux Ubuntu

**Script**
Unknown

**Script Version**
Downloaded today

**Describe the bug**
Changes in the "Artist Folder Format" field under "Media Management" does is not reflected in the Library view when I "preview the rename". However, changes in the standard track format and multi disc format ARE reflected. Specifically, the preview of the Artist Folder Format is "stuck" with "{artist name} {Artist Disambiguation}" when doing the library preview. However, you can change in Media Format to just "{Artist Name}" (meaning the extended.conf autoconfiguration is disabled).  

**To Reproduce**
1. Go to Media Management, modify the "Artist Folder Format" to be "{Artist Name}". 
2. Click Save Changes. 
3. Go to Library and open an album, then click on "Preview Rename". Observe that the Artist Name also includes a distinguishing trait about the artist (Adele (UK soul+jazz singer)) vs. just the Artist name.
4. Restart the container and observe the same issue (correct setting sticks in media management). 

**Expected behavior**
When disabling the 'auto' section in extended.conf, and then changing the "artist folder format", the user chosen format should be reflected in the album rename preview.

**Logs/Screenshots**
![2024-02-04_21-12-01](https://github.com/RandomNinjaAtk/arr-scripts/assets/30213019/c12ac0aa-8e17-47d8-85be-ea4125c1f7a6)
![2024-02-04_21-24-07](https://github.com/RandomNinjaAtk/arr-scripts/assets/30213019/beca3765-9695-4556-99b4-c241296953c9)

**Additional context**
None

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by RandomNinjaAtk** [comment]
Your question is a lidarr usage question, you should ask Lidarr support how to rename the folders. If the setting sticks as you said it did, then there is no bug.

**Comment by RandomNinjaAtk** [comment]
https://wiki.servarr.com/lidarr/faq#how-can-i-rename-my-artist-folders
