### ISSUE TITLE
[Feature request] - Lidarr - Make sleep timer adjustable

### ISSUE THREAD

**Issue by jaycedk** [RandomNinjaAtk/arr-scripts#18]
**Application**
Lidarr

**Script**
Video.service.bash

**Script Version**
1.7

**Describe the Feature request**
I would love to be able to adjust the sleep 15m, to like 24h
This is just my preference, that is why i would like to see a setting that could adjust that. 
So that everyone can set there sleep timer, to there preference. 

I think the is no line 740 : sleep 15m

This could be extended to all Arrs.

**Comment by jaycedk** [comment]
Ohh wow RandomNinjaAtk, slow down 😎
It's weekend 😁

**Comment by RandomNinjaAtk** [comment]
Update to the latest

**Comment by jaycedk** [comment]
Ok super, will test it right now 😀

**Comment by jaycedk** [comment]
Nice that did it 👍
Perfect thank you 😀
