### ISSUE TITLE
[BUG] - Lidarr - Each letter in "Release Type" metadata is separated with ;

### ISSUE THREAD

**Issue by Coder84619** [RandomNinjaAtk/arr-scripts#182]
**Application**
Lidarr

**Host platform**
Linux Ubuntu x64

**Script**
Unknown

**Script Version**
Latest as of Feb 6

**Describe the bug**
When viewing the embedded metadata of a track, the "Release Type" field has each letter separated by a ";". For example, EP becomes "e; p" and album is "a; l; b; u; m;". 

![2024-02-06_21-03-22](https://github.com/RandomNinjaAtk/arr-scripts/assets/30213019/0db9b791-7fc3-4b77-adf7-837d686be33a)
![2024-02-06_20-56-15](https://github.com/RandomNinjaAtk/arr-scripts/assets/30213019/c9abfb1a-e308-46c0-aee0-37d12215fe91)

**To Reproduce**
1. Have Lidarr auto-download content from Deezer.
2. Open track in Picard and review metadata.
3. Review "Release Type" metadata.
4. Observe that each letter is separated by a ; and a space. 

**Expected behavior**
The release type should not have separated letters. E.g. should be "album", or "ep". 

**Logs/Screenshots**
Above. 

**Additional context**

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by RandomNinjaAtk** [comment]
#170
