### ISSUE TITLE
[QUESTION] - Lidarr - Downloaded Album Scan

### ISSUE THREAD

**Issue by JaydenJinx** [RandomNinjaAtk/arr-scripts#184]
**Application**
Lidarr

**Host platform**
Unraid. Ryzen 2700X. Gigabit internet. 

**Script**
Audio

**Script Version**
3.7

**Description**
It seems like every time an album will be downloaded via Deezer it takes 2-4 minutes to run the "Downloaded Albums Scan" task on Lidarr, halting all other downloads. The next album's download doesn't start until this task is complete. Is this supposed to take that long or is something wrong? 

**Logs/Screenshots**
![Screenshot 2024-02-08 at 5 19 20 PM](https://github.com/RandomNinjaAtk/arr-scripts/assets/37884702/343d49ac-ba3c-4281-8a1c-0adc1a4ee194)

**Comment by RandomNinjaAtk** [comment]
The download folder is purged after every download... So yes, it waits for Lidarr to complete before moving on...
