### ISSUE TITLE
Adjust Media Management Settings in Sonarr

### ISSUE THREAD

**Issue by stayupthetree** [RandomNinjaAtk/arr-scripts#185]
Is it possible to adjust what settings are configured by the scripts? The only thing I want to be able to do is enable "Unmonitor Deleted Episodes". If I manually enable it, whenever the container restarts it reverts back. I have Plex handle removing TV shows I watch after a week. This works well but if they remain monitored in Sonarr they will get redownloaded.

**Comment by RandomNinjaAtk** [comment]
….
https://github.com/RandomNinjaAtk/arr-scripts/blob/76c02a33447b509138cd779d442987fc47f02338/sonarr/extended.conf#L20

**Comment by stayupthetree** [comment]
Doh! Thought about that but wasn't sure it wouldnt affect anything else. Thanks! Sorry to bother
