### ISSUE TITLE
[BUG]  ARLChecker fail

### ISSUE THREAD

**Issue by zestysoft** [RandomNinjaAtk/arr-scripts#189]
ARL Token Check Complete. Sleeping for 24hrs...
sleep: invalid time interval ‘’
Try 'sleep --help' for more information.

Looks like the code doesn't have a default in case the variable doesn't exist in the conf file.  Any existing deployment wouldn't have that variable, so the next time they re-deploy the container, they're gonna get this.  Unfortunately, because sleep is broken, this will run constantly and hammer away at Deezer.

**Comment by hockeygoalie35** [comment]
Ah, good catch! On it.

**Comment by hockeygoalie35** [comment]
Pull Request created.

**Comment by hockeygoalie35** [comment]
Hey @zestysoft, please reboot your container and let me know if the problem's resolved.

**Comment by Borderpatrol1987** [comment]
Im having the same issue, a reboot didnt fix it for me.

**Comment by hockeygoalie35** [comment]
@Borderpatrol1987 

Try removing ARLChecker from custom-services and then reboot. The new one should be force-downloaded.

**Comment by Borderpatrol1987** [comment]
That seemed to do the trick. Now to fix my library cause lidarr seems to have "forgotten" it at the same time this happened.

**Comment by zestysoft** [comment]
Before your fix, I added the missing configuration to the conf file to solve this issue.

However, I commented that out and restarted the container and it looks like the check is working:

```
Interval Fallback
ARL Token Check Complete. Sleeping for 24h.
```

**Comment by zestysoft** [comment]
@hockeygoalie35 ty for the quick fix!
