### ISSUE TITLE
[FEATURE] - APP NAME - is there a way to ignore clean versions

### ISSUE THREAD

**Issue by Darotondo** [RandomNinjaAtk/arr-scripts#190]
It seems the script favors clean versions heavily compares to explicit, just wanted to see if there was a way to change this or just a limitation with auto matching

**Comment by RandomNinjaAtk** [comment]
It prefers explicit by default, you can see that by reading the logs…

Also:
https://github.com/RandomNinjaAtk/arr-scripts/blob/4121d3bea22fbac04b3ac8af2fa411c7f8423d72/lidarr/extended.conf#L47
