### ISSUE TITLE
QueCleaner Errors on Non-standard Arr Name

### ISSUE THREAD

**Issue by Bait-Fish** [RandomNinjaAtk/arr-scripts#2]
My Lidarr-extended container is named "LidarrA-F" which appears to causes the following error to repeat. All that is logged to QueueCleaner.txt are lines like this every couple of seconds.

2023-05-03 14:55:10 :: QueueCleaner :: 1.0.3 :: ERROR :: Arr app not detected, exiting...

From the config.xml
<InstanceName>LidarrA-F</InstanceName>

I believe QueCleaner is expecting only "Lidarr".

**Comment by RandomNinjaAtk** [comment]
There is no reason to change the name. Your right that it's likely the issue, since you changed it. The script is universal, the name matters for detecting the correct application.

**Comment by RandomNinjaAtk** [comment]
Fixed
