### ISSUE TITLE
[BUG] - Lidarr - Broken Pipe

### ISSUE THREAD

**Issue by baxterblk** [RandomNinjaAtk/arr-scripts#201]
**Application**
Lidarr

**Host platform**
Docker-Compose - Linux Server

**Script**
Artwork Extractor
Lyric Extractor
BeetsTagger

**Script Version**
Artwork Extractor 1.2
Lyric Extractor 1.5
BeetsTagger 1.8

**Describe the bug**
Importing songs triggers these bash scripts which output an error. Likely something related to jq.

**To Reproduce**

**Expected behavior**
I'd like to be able to use these scripts as intended without error.

**Logs**
[Info] DownloadDecisionMaker: No results found 
[Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0 
2024-02-16 19:42:18 :: QueueCleaner :: 1.7 :: Starting...
2024-02-16 19:42:18 :: QueueCleaner :: 1.7 :: No items in queue to clean up
2024-02-16 19:42:18 :: QueueCleaner :: 1.7 :: Sleeping 5m...
[Info] ImportListSyncService: Starting Import List Sync 
[Info] ImportListSyncService: No list items to process 
2024-02-16 19:47:24 :: QueueCleaner :: 1.7 :: Starting...
2024-02-16 19:47:24 :: QueueCleaner :: 1.7 :: No items in queue to clean up
2024-02-16 19:47:24 :: QueueCleaner :: 1.7 :: Sleeping 5m...
2024-02-16 19:48:13 :: Audio :: 2.32 :: 1 :: missing :: 2 of 795 :: Guns N’ Roses :: Use Your Illusion :: Album :: LIDARR IMPORT NOTIFICATION SENT! :: /config/extended/downloads/audio/incomplete/audio/complete/Guns N’ Roses-Use Your Illusion Super Deluxe (2022)-MP3-372570847-DEEZER
2024-02-16 19:48:13 :: Audio :: 2.32 :: STATUS :: LIDARR BUSY :: Pausing/waiting for all active Lidarr tasks to end...
[Info] ImportDecisionMaker: Reading file 1/77 
[Info] ImportDecisionMaker: Reading file 2/77 
[Info] ImportDecisionMaker: Reading file 3/77 
[Info] ImportDecisionMaker: Reading file 4/77 
[Info] ImportDecisionMaker: Reading file 5/77 
[Info] ImportDecisionMaker: Reading file 6/77 
[Info] ImportDecisionMaker: Reading file 7/77 
[Info] ImportDecisionMaker: Reading file 8/77 
[Info] ImportDecisionMaker: Reading file 9/77 
[Info] ImportDecisionMaker: Reading file 10/77 
[Info] ImportDecisionMaker: Reading file 11/77 
[Info] ImportDecisionMaker: Reading file 12/77 
[Info] ImportDecisionMaker: Reading file 13/77 
[Info] ImportDecisionMaker: Reading file 14/77 
[Info] ImportDecisionMaker: Reading file 15/77 
[Info] ImportDecisionMaker: Reading file 16/77 
[Info] ImportDecisionMaker: Reading file 17/77 
[Info] ImportDecisionMaker: Reading file 18/77 
[Info] ImportDecisionMaker: Reading file 19/77 
[Info] ImportDecisionMaker: Reading file 20/77 
[Info] ImportDecisionMaker: Reading file 21/77 
[Info] ImportDecisionMaker: Reading file 22/77 
[Info] ImportDecisionMaker: Reading file 23/77 
[Info] ImportDecisionMaker: Reading file 24/77 
[Info] ImportDecisionMaker: Reading file 25/77 
[Info] ImportDecisionMaker: Reading file 26/77 
[Info] ImportDecisionMaker: Reading file 27/77 
[Info] ImportDecisionMaker: Reading file 28/77 
[Info] ImportDecisionMaker: Reading file 29/77 
[Info] ImportDecisionMaker: Reading file 30/77 
[Info] ImportDecisionMaker: Reading file 31/77 
[Info] ImportDecisionMaker: Reading file 32/77 
[Info] ImportDecisionMaker: Reading file 33/77 
[Info] ImportDecisionMaker: Reading file 34/77 
[Info] ImportDecisionMaker: Reading file 35/77 
[Info] ImportDecisionMaker: Reading file 36/77 
[Info] ImportDecisionMaker: Reading file 37/77 
[Info] ImportDecisionMaker: Reading file 38/77 
[Info] ImportDecisionMaker: Reading file 39/77 
[Info] ImportDecisionMaker: Reading file 40/77 
[Info] ImportDecisionMaker: Reading file 41/77 
[Info] ImportDecisionMaker: Reading file 42/77 
[Info] ImportDecisionMaker: Reading file 43/77 
[Info] ImportDecisionMaker: Reading file 44/77 
[Info] ImportDecisionMaker: Reading file 45/77 
[Info] ImportDecisionMaker: Reading file 46/77 
[Info] ImportDecisionMaker: Reading file 47/77 
[Info] ImportDecisionMaker: Reading file 48/77 
[Info] ImportDecisionMaker: Reading file 49/77 
[Info] ImportDecisionMaker: Reading file 50/77 
[Info] ImportDecisionMaker: Reading file 51/77 
[Info] ImportDecisionMaker: Reading file 52/77 
[Info] ImportDecisionMaker: Reading file 53/77 
[Info] ImportDecisionMaker: Reading file 54/77 
[Info] ImportDecisionMaker: Reading file 55/77 
[Info] ImportDecisionMaker: Reading file 56/77 
[Info] ImportDecisionMaker: Reading file 57/77 
[Info] ImportDecisionMaker: Reading file 58/77 
[Info] ImportDecisionMaker: Reading file 59/77 
[Info] ImportDecisionMaker: Reading file 60/77 
[Info] ImportDecisionMaker: Reading file 61/77 
[Info] ImportDecisionMaker: Reading file 62/77 
[Info] ImportDecisionMaker: Reading file 63/77 
[Info] ImportDecisionMaker: Reading file 64/77 
[Info] ImportDecisionMaker: Reading file 65/77 
[Info] ImportDecisionMaker: Reading file 66/77 
[Info] ImportDecisionMaker: Reading file 67/77 
[Info] ImportDecisionMaker: Reading file 68/77 
[Info] ImportDecisionMaker: Reading file 69/77 
[Info] ImportDecisionMaker: Reading file 70/77 
[Info] ImportDecisionMaker: Reading file 71/77 
[Info] ImportDecisionMaker: Reading file 72/77 
[Info] ImportDecisionMaker: Reading file 73/77 
[Info] ImportDecisionMaker: Reading file 74/77 
[Info] ImportDecisionMaker: Reading file 75/77 
[Info] ImportDecisionMaker: Reading file 76/77 
[Info] ImportDecisionMaker: Reading file 77/77 
[Info] TrackGroupingService: Grouping 77 tracks 
[Info] IdentificationService: Identifying album 1/1 
[Info] ImportApprovedTracks: Importing album 1/1 
[Info] ImportApprovedTracks: Importing 77 tracks 
[Info] ImportListSyncService: Starting Import List Sync 
[Info] ImportListSyncService: No list items to process 
[Error] LyricExtractor.bash: Error: writing output failed: Broken pipe 
[Error] ArtworkExtractor.bash: Error: writing output failed: Broken pipe 
2024-02-16 19:52:29 :: QueueCleaner :: 1.7 :: Starting...
2024-02-16 19:52:29 :: QueueCleaner :: 1.7 :: No items in queue to clean up
2024-02-16 19:52:29 :: QueueCleaner :: 1.7 :: Sleeping 5m...

**Additional context**

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by RandomNinjaAtk** [comment]
#87
