### ISSUE TITLE
[FEATURE] - Lidarr - Upgrade existing files

### ISSUE THREAD

**Issue by Makario1337** [RandomNinjaAtk/arr-scripts#202]
**Is your feature request related to a problem? Please describe.**
No, I would like the Audio Script to upgrade existing mp3 files to lossless if available

**Describe the solution you'd like**
A new feature, which can be enabled in the extended.conf.

**Describe alternatives you've considered**
Doing it manually.

**Comment by RandomNinjaAtk** [comment]
If lidarr is configured properly, it should already do this but using the Cutoff list....
