### ISSUE TITLE
How to set to not always copy video codec sma.ini

### ISSUE THREAD

**Issue by neilanthonystuckey** [RandomNinjaAtk/arr-scripts#203]
**Application**
 SABnzbd

**Host platform**
Debian bookworm x86

**Script**
video.bash

**Script Version**
v1.0.5

**Describe the bug**
I modified /config/scripts/sma.ini to use qsv and to use codec of h264qsv but it always copies the original codec. I have too many non HEVC clients to transcode a lot of streams. Would like to be able to encode everything to mp4, x264 with ac3 audio for direct stream playback in plex for any client that cant handle 4k hevc or 4k 264. 

**To Reproduce**
Run video.bash in sabnzbd

**Expected behavior**
To not always copy the video codecs and audio codecs

**Logs/Screenshots**
none

**Additional context**
sma.ini

[Converter]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
threads = 0
hwaccels = qsv
hwaccel-decoders = h264_qsv, hevc_qsv, mpeg2_qsv, vc1_qsv, vp8_qsv, vp9_qsv
hwdevices = /dev/dri/renderD128
hwaccel-output-format = qsv:qsv
output-directory =
output-format = mp4
output-extension = mp4
temp-extension =
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to =
move-to =
delete-original = True
process-same-extensions = True
bypass-if-copying-all = True
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = -fflags,+genpts
postopts =
regex-directory-replace = [^\w\-_\. ]
output-directory-space-ratio = 0.0

[Video]
codec = h264qsv,
max-bitrate = 0
bitrate-ratio =
crf = 30
crf-profiles =
preset =
codec-parameters =
dynamic-parameters = False
max-width = 0
profile =
max-level = 0.0
pix-fmt =
prioritize-source-pix-fmt = True
filter =
force-filter = False

[Audio]
codec = ac3
languages = eng
default-language = eng
first-stream-of-language = True
allow-language-relax = True
relax-to-default = False
channel-bitrate = 128
variable-bitrate = 0
max-bitrate = 160
max-channels = 2
filter =
profile =
force-filter = False
sample-rates =
sample-format =
copy-original = False
aac-adtstoasc = False
ignored-dispositions =
force-default = False
unique-dispositions = True
stream-codec-combinations =
include-original-language = True

Thanks for your time.

**Comment by RandomNinjaAtk** [comment]
Honestly not sure HW accelerated codecs work, you should try with typical h264, x264 first to see if it works as intended...

If HW accelerated codecs work, its most likely going to be vaapi, and not qsv.

You might just need to experiment and manually figure out what works. I welcome a PR to improve it if needed...

**Comment by RandomNinjaAtk** [comment]
My advice, is to probably just try to source files that are closer to the format you want to begin with and possibly only modify the audio. It will be much faster than doing conversions and your not transcoding an already transcoded file...

**Comment by RandomNinjaAtk** [comment]
No response, closing…
