### ISSUE TITLE
[BUG] - Containers not able to run in parallel

### ISSUE THREAD

**Issue by Hietala** [RandomNinjaAtk/arr-scripts#205]
**Application**
All of the arrs

**Host platform**
Unraid/

**Script**
universal/functions.bash

**Script Version**
3.2

**Describe the bug**
I setup two Lidarr containers to speed up the artist download process, one has albums to download and the other one gets lidarr list from the first container and downloads singles and EP albums from the artists. Current script does not allow lidarr to run on any unofficial port.

**To Reproduce**
Setup second container and you wont be able to run the script.

**Expected behavior**
I would expect them to be able to run in parallel.

**Logs/Screenshots**
"Lidarr is not ready, sleeping until valid response..."

**Additional context**
I created a fork on my own page, I can create a pull request for this if the bug fix seems acceptable.

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by RandomNinjaAtk** [comment]
You can run multiple containers, what your experiencing is a user misconfiguration issue on your part… without knowing the specifics of how you configured it, can’t help you much. But I can tell you this is not a bug because I already do this and it’s just a problem on your end…

if I had to guess, you modified the port when you should never be changing port. And changing the lidarr internal software port is not needed when running multiple containers…

But I’m just making an assumption/guess…

**Comment by Hietala** [comment]
It's not an user error, I kinda hastily wrote this and forgot to mention how I setup them. Thats my bad.

I have a VPN container which I use for all of my arrs, meaning they all share the same docker network, hence I cannot use the same port for the second Lidarr container and I was forced to change it. They are individual containers but connect to the VPNs docker network.

**Comment by RandomNinjaAtk** [comment]
The method you are using to change the ports is incorrect. You don’t change the internal port, only change the exposed port.

As I said, I’m already running multiple containers, so it’s a non issue.

**Comment by Hietala** [comment]
`[Fatal] ConsoleApp: Failed to bind to address http://[::]:8686: address already in use. This can happen if another instance of Lidarr is already running another application is using the same port (default: 8686)`

I'm not sure how yours is setup but I simply cannot get rid of this error unless I change the internal port. However I have no trouble maintaining my own fork of this with the fix for my issue, just thought to post here if it was issue affecting other people as well.

**Comment by hockeygoalie35** [comment]
Agreed it’s a container issue. If you’re using docker compose, here’s how you would bind the container internal port 8686 to 3535 as I did in a second lidarr container:

![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/7758029/78a884ed-ea09-4b90-adcf-f326fac78565)
