### ISSUE TITLE
[FEATURE] - Unmapped file remover for Lidarr

### ISSUE THREAD

**Issue by Glynax** [RandomNinjaAtk/arr-scripts#21]
As per the devs themselves having unmapped files in lidarr greatly slows down lidarr. I let it 100% handle my music so there should in theory never be any unmapped and yet every few days there's more in there for me to remove.

I noticed you have an unmapped deleter for radarr, just wondering if something similar could be done for lidarr

Alternative is just doing it manually like I do now

**Comment by RandomNinjaAtk** [comment]
It’s a good idea, I’ve honestly never looked into it for the other apps. I developed the radarr one because at some point I had needed it.

**Comment by RandomNinjaAtk** [comment]
This should now be complete with the latest changes, the script at least removes the data, I'm not yet sure if Lidarr will pickup on that though.. So more work might need to be done...

**Comment by Glynax** [comment]
Just to note I'm 95% sure it also removes them from lidarr. I just checked and there's much less unmapped files from last week, and I haven't intervened, just your script. There's no log for me to check though that I see in lidarr to confirm

**Comment by RandomNinjaAtk** [comment]
There should be a log from the script and the recent updates fixed the lidarr info

**Comment by Glynax** [comment]
Just wanted to confirm it's definitely working. I see the log now after the update.

**Comment by cherryontopknife** [comment]
It'd be nice to see this feature explained in the readme, or in the script itself. I thought this cleaned the file import queue, but it just deletes stuff without confirmation. IMO, there should be more weight, or instruction surrounding, flipping a switch that could potentially delete thousands of files.

**Comment by RandomNinjaAtk** [comment]
@cherryontopknife 

Wiki is open for edits, feel free to enhance the readme’s by writing a PR.
