### ISSUE TITLE
[Proxmox LXC Container] - Lidarr - Ability to use scripts on Proxmox LXC Container?

### ISSUE THREAD

**Issue by Simpuhl** [RandomNinjaAtk/arr-scripts#213]
**Is your feature request related to a problem? Please describe.**
I switched from using docker to using an Proxmox LXC Container for my Lidarr, things run a lot more smoothly, but I was hoping this would somehow work for the Proxmox LXC Container also. 

**Describe the solution you'd like**
Would love Proxmox LXC Container support with install instructions.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by RandomNinjaAtk** [comment]
These are just bash scripts, you can use the scripts here with a little bit of modification to make it fit your needs. As I don't have this kind of setup or configuration, it is not something that I will support unfortunately. 

Examples would be to install all dependencies from the setup script. Then schedule cron jobs to execute the scripts. You might then need to modify file paths or other things in the scripts to accommodate your own custom locations and etc...

**Comment by Simpuhl** [comment]
Thank you for the reply. I will test thing out. Appreciate it

**Comment by Simpuhl** [comment]
> These are just bash scripts, you can use the scripts here with a little bit of modification to make it fit your needs. As I don't have this kind of setup/configuration, it is not something that I will support unfortunately.
> 
> Examples would be to install all dependencies from the setup script. Then schedule cron jobs to execute the scripts. You might then need to modify file paths or other things in the scripts to accommodate your own custom locations and etc...
> 
> The wiki is open for edits, if you get it working and would like to post a guide for others.

Hey so I've been messing with this all day, and I am having trouble getting them to work, obviously not your problem but if this is something you ever end up possibly wanting to get working, I'd be willing to donate $$ for it.
