### ISSUE TITLE
[FEATURE] - Radarr/Sonarr - Support for non-standard port configs

### ISSUE THREAD

**Issue by quadcom** [RandomNinjaAtk/arr-scripts#214]
I saw another post about non-standard ports (https://github.com/RandomNinjaAtk/arr-scripts/issues/31), and I hope it would be possible to allow this to work.

My Radarr/Sonarr containers run on a separate VLAN with unique IPs on that subnet. In that case, port numbers are unnecessary, as each instance is seen as its own system. As such, I configured both Radarr instances and Sonarr to use standard port 80 (all of my services are for internal use only and are not exposed to the internet). 

There must be something in the scripts that is hard-coded to use the standard Radarr/Sonarr ports. Can that not be configured using the APP config.xml file variable?

**Comment by RandomNinjaAtk** [comment]
The API script uses hardcoded ports to detect which application is used... That way I don't have to maintain 3 versions of the same script.... 

Now maybe this could be solved using another method like the config file specifying which api to use per app, but that would likely break all existing configurations/installations. So not sure what could be done about it... I haven't had the cycles to work on anything but bug fixing for the most part and if it ain't broke don't fix it.... I also can't account for every use case out there, these are designed to work with my particular configuration and published here for others to use as a nice benefit/perk... So if it's not in my direct usage, I don't really support it.

**Comment by RandomNinjaAtk** [comment]
I think the latest https://github.com/RandomNinjaAtk/arr-scripts/commit/c0ac258d5b20c5f617748811c87f56cbc6fb406b fixes this!

I had an idea and pushed the change, it should work.... See if that resolves your request...

**Comment by quadcom** [comment]
Awesome! Thanks for giving it some thought.

I had a thought too. I saw the API check code and thought I could modify that to match my port config. Sure, it would change on restart, possibly. But it might get it working. I don't restart it all that often.

I'll try the new version and see how it works.

Thx again!

**Comment by quadcom** [comment]
Works like a charm!!!!!!
