### ISSUE TITLE
[BUG] - Radarr - InvalidMoviesAutoCleaner runs regardless of false setting

### ISSUE THREAD

**Issue by quadcom** [RandomNinjaAtk/arr-scripts#215]
**Application**
Radarr

**Host platform**
Unraid

**Script**
InvalidMoviesAutoCleaner

**Script Version**
InvalidMovieAutoCleaner="1.1"

**Describe the bug**
I am seeing the logs that InvalidMoviesAutoCleaner knows that it is disabled, but it runs anyway (from what I am reading)

**To Reproduce**
I'm not sure how to reproduce. I flushed all the extended scripts and restarted Radarr. The init script DL'd all the latest versions. I configured the conf as below;

```
##### SCRIPT ENABLEMENT
enableAutoConfig="true" # true = enabled :: Enables AutoConfig script to run after startup
enableExtras="true" # true = enabled :: Enables Extras and AutoExtras scripts to run in the background and during import process
enableRecyclarr="true" # true = enabled :: Enables Recyclarr to run
enableQueueCleaner="false" # true = enabled :: Enables QueueCleaner Script that automatically removes stuck downloads that cannot be automatically imported
enableUnmappedFolderCleaner="false" # true = enabled :: Purges any folders that are considered Unmapped in Radarr
enableInvalidMoviesAutoCleaner="false" # true = enabled :: Enables InvalidMoviesAutoCleaner script to run, removes movies that are no longer mapped to TMDB site
```

**Expected behavior**
I expected all functions marked as 'false' in the configuration not to run and would not produce any log entries.

**Logs/Screenshots**

```
2024-03-24 17:07:38 :: InvalidMoviesAutoCleaner :: 1.1 :: Script starting...
2024-03-24 17:07:38 :: InvalidMoviesAutoCleaner :: 1.1 :: Script is not enabled, enable by setting enableInvalidMoviesAutoCleaner to "true" by modifying the "/config/extended.conf" config file...
2024-03-24 17:07:38 :: InvalidMoviesAutoCleaner :: 1.1 :: Sleeping (infinity)
2024-03-24 17:07:38 :: InvalidMoviesAutoCleaner :: 1.1 :: No invalid movies (tmdbid) reported by Radarr health check, skipping...
2024-03-24 17:07:38 :: InvalidMoviesAutoCleaner :: 1.1 :: Script sleeping for 1h...
```

This log entry repeats every hour as per the extended.conf config even though it is disabled in the same config file.

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by RandomNinjaAtk** [comment]
Should be fixed with the latest change.
