### ISSUE TITLE
[BUG] - LIDARR - Added IMVDB to MusicBrainz artist pages and they were automatically added. Still no music videos downloading.

### ISSUE THREAD

**Issue by nothing2obvi** [RandomNinjaAtk/arr-scripts#219]
**Application**
Lidarr

**Host platform**
Docker Desktop for Mac 4.28.0

**Script**
Video.service.bash

**Script Version**
3.7

**Describe the bug**
I added IMVDB links to artists on MusicBrainz and they were automatically accepted (no voting required). The next day, I then restarted Lidarr and the music videos from the artists' respective IMVDB pages are still not downloading. The artists are [Dance Gavin Dance](https://musicbrainz.org/artist/16456fed-c9f2-4adf-b6ea-97b648c474d2/edit) and [Khruangbin](https://musicbrainz.org/artist/aea4c9b9-9f8d-49dc-b2ca-57d6f26e8634/edit). 

Is this just a matter of waiting?

**To Reproduce**
1. Add IMVDB links to artist pages on MusicBrainz, ensuring there are is at least 1 music video on each artist's respective IMVDB page.
2. Links are automatically accepted, with no voting required.
3. Restart Lidarr
4. Script still does not download music videos for those artists.

**Expected behavior**
The script should download catalogued music videos for those artists.

**Logs/Screenshots**
```
03/25/2024
02:42:04 PM
2024-03-25 14:42:04 :: Video :: 3.7 :: 3/21 :: Dance Gavin Dance :: Checking for IMVDB Slug
03/25/2024
02:42:04 PM
2024-03-25 14:42:04 :: Video :: 3.7 :: 3/21 :: Dance Gavin Dance :: IMVDB :: ERROR :: Slug Not Found, skipping...
```

```
03/25/2024
02:42:04 PM
2024-03-25 14:42:04 :: Video :: 3.7 :: 8/21 :: Khruangbin :: Checking for IMVDB Slug
03/25/2024
02:42:04 PM
2024-03-25 14:42:04 :: Video :: 3.7 :: 8/21 :: Khruangbin :: IMVDB :: ERROR :: Slug Not Found, skipping...
```

**Additional context**
None

**Comment by RandomNinjaAtk** [comment]
Lidarr has to have that in its metadata for an artist, the script cannot check the website.

If you view the artist in lidarr and check for links, if it’s not listed. The script will not find it, you can try refreshing the artist or contact lidarr support.

You did the correct thing, just depends on lidarr to have the info, nothing to do on this end.

**Comment by nothing2obvi** [comment]
Sounds good. Thanks!
