### ISSUE TITLE
[BUG] - Radarr - SMA Processing Error

### ISSUE THREAD

**Issue by lons81** [RandomNinjaAtk/arr-scripts#220]
**Application**
Radarr

**Host platform**
Unraid

**Describe the bug**
Fresh installation of radarr, started & import some movies.
arr-script-radarr installed and reboot of radarr

It finds some trailer and i see the download in my folder.
But then i got an "SMa Processing Error" and my file is deleted

Error Log:

`2024-03-27 13:49:51 :: Extras :: 1.2 :: Cookies File Not Found!

2024-03-27 13:49:51 :: Extras :: 1.2 :: MY_MOVIE :: Searching for "de-DE" extras...

2024-03-27 13:49:51 :: Extras :: 1.2 :: MY_MOVIE :: 3 Extras Found!

2024-03-27 13:49:51 :: Extras :: 1.2 :: MY_MOVIE :: 1 of 3 :: Trailer :: MY_MOVIE ≣ 2010 ≣ Trailer (1VjGPAmC3Qo) :: Downloading (yt-dlp :: bestvideo*+bestaudio/best)...

[youtube] Extracting URL: https://www.youtube.com/watch?v=1VjGPAmC3Qo

[youtube] 1VjGPAmC3Qo: Downloading webpage

[youtube] 1VjGPAmC3Qo: Downloading ios player API JSON

[youtube] 1VjGPAmC3Qo: Downloading android player API JSON

WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] 1VjGPAmC3Qo: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] 1VjGPAmC3Qo: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] 1VjGPAmC3Qo: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 1VjGPAmC3Qo: Downloading player 2923e6f1
[youtube] 1VjGPAmC3Qo: Downloading m3u8 information
[info] 1VjGPAmC3Qo: Downloading 1 format(s): 137+251
[info] There are no subtitles for the requested languages
[download] Destination: /movies/Fantasy/MY_MOVIE (2010)/trailers/MY_MOVIE 2010 Trailer.f137.mp4
[download] 100% of   47.41MiB in 00:00:06 at 7.85MiB/s   
[download] Destination: /movies/Fantasy/MY_MOVIE (2010)/trailers/MY_MOVIE 2010 Trailer.f251.webm
[download] 100% of    2.12MiB in 00:00:00 at 6.42MiB/s   
[Merger] Merging formats into "/movies/Fantasy/MY_MOVIE (2010)/trailers/MY_MOVIE 2010 Trailer.mkv"
Deleting original file /movies/Fantasy/MY_MOVIE (2010)/trailers/MY_MOVIE 2010 Trailer.f251.webm (pass -k to keep)
Deleting original file /movies/Fantasy/MY_MOVIE (2010)/trailers/MY_MOVIE 2010 Trailer.f137.mp4 (pass -k to keep)
[EmbedSubtitle] There aren't any subtitles to embed
2024-03-27 13:50:01 :: Extras :: 1.2 :: MY_MOVIE :: 1 of 3 :: Trailer :: MY_MOVIE ≣ 2010 ≣ Trailer (1VjGPAmC3Qo) :: Compete
Traceback (most recent call last):
  File "/usr/local/sma/manual.py", line 5, in <module>
    import guessit
ModuleNotFoundError: No module named 'guessit'
2024-03-27 13:50:01 :: Extras :: 1.2 :: MY_MOVIE :: 1 of 3 :: Trailer :: MY_MOVIE ≣ 2010 ≣ Trailer :: ERROR :: SMA Processing Error
2024-03-27 13:50:01 :: Extras :: 1.2 :: MY_MOVIE :: 1 of 3 :: Trailer :: MY_MOVIE ≣ 2010 ≣ Trailer :: INFO: deleted: /movies/Fantasy/MY_MOVIE (2010)/trailers/MY_MOVIE 2010 Trailer.mkv
2024-03-27 13:50:01 :: Extras :: 1.2 :: MY_MOVIE :: 2 of 3 :: Trailer :: MY_MOVIE TRAILER DEUTSCH 1 (HD) (wtoSd-O8SkU) :: Downloading (yt-dlp :: bestvideo*+bestaudio/best)...
`
Thanks, Lons

**Comment by hockeygoalie35** [comment]
Same issue as #216 , Will have a PR later today for Radarr, Readarr, Sabnzbd and Sonarr.

**Comment by lons81** [comment]
Thanks for Reply,

i try to install jellyfish, but same error after restart...

staring error:
`OK: 599 MiB in 225 packages
************ install python packages ************
Requirement already satisfied: excludarr in /usr/lib/python3.11/site-packages (1.0.7)
Requirement already satisfied: yq in /usr/lib/python3.11/site-packages (3.2.3)
Requirement already satisfied: typer>=0.4.1 in /usr/lib/python3.11/site-packages (from excludarr) (0.11.0)
Requirement already satisfied: loguru>=0.6.0 in /usr/lib/python3.11/site-packages (from excludarr) (0.7.2)
Requirement already satisfied: rich>=12.4.1 in /usr/lib/python3.11/site-packages (from excludarr) (13.7.1)
Requirement already satisfied: requests>=2.27.1 in /usr/lib/python3.11/site-packages (from excludarr) (2.31.0)
Requirement already satisfied: PyYAML>=6.0 in /usr/lib/python3.11/site-packages (from excludarr) (6.0.1)
Requirement already satisfied: pyarr>=3.1.3 in /usr/lib/python3.11/site-packages (from excludarr) (5.2.0)
Requirement already satisfied: xmltodict>=0.11.0 in /usr/lib/python3.11/site-packages (from yq) (0.13.0)
Requirement already satisfied: tomlkit>=0.11.6 in /usr/lib/python3.11/site-packages (from yq) (0.12.4)
Requirement already satisfied: argcomplete>=1.8.1 in /usr/lib/python3.11/site-packages (from yq) (3.2.3)
Requirement already satisfied: overrides<8.0.0,>=7.3.1 in /usr/lib/python3.11/site-packages (from pyarr>=3.1.3->excludarr) (7.7.0)
Requirement already satisfied: types-requests<3.0.0.0,>=2.28.11.17 in /usr/lib/python3.11/site-packages (from pyarr>=3.1.3->excludarr) (2.31.0.20240311)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.11/site-packages (from requests>=2.27.1->excludarr) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests>=2.27.1->excludarr) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests>=2.27.1->excludarr) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.11/site-packages (from requests>=2.27.1->excludarr) (2024.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/lib/python3.11/site-packages (from rich>=12.4.1->excludarr) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/lib/python3.11/site-packages (from rich>=12.4.1->excludarr) (2.17.2)
Requirement already satisfied: click>=8.0.0 in /usr/lib/python3.11/site-packages (from typer>=0.4.1->excludarr) (8.1.7)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/lib/python3.11/site-packages (from typer>=0.4.1->excludarr) (4.10.0)
Requirement already satisfied: mdurl~=0.1 in /usr/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=12.4.1->excludarr) (0.1.2)
************ setup SMA ************
************ setup directory ************
************ download repo ************
************ create logging file ************
************ install pip dependencies ************
error: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
error: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).`

**Comment by hockeygoalie35** [comment]
Yeah, it's a two part issue, Jellyfish being one of them. The other, in `setup.bash`, every pip statement needs a `--break-system-packages` flag included.

**Comment by RandomNinjaAtk** [comment]
Pushed a change, see if that resolves it

**Comment by RandomNinjaAtk** [comment]
@lons81 is this resolved?

**Comment by lons81** [comment]
Perfect, now it works like a charm
Thanks
