### ISSUE TITLE
[BUG] - Lidarr - Keep "Rescan Artist Folder after Refresh" setting after restart

### ISSUE THREAD

**Issue by steve1977** [RandomNinjaAtk/arr-scripts#226]
**Application**
Lidarr

**Host platform**
Unraid

**Describe the bug**
I have set "Rescan Artist Folder after Refresh" to "Never". However, this setting changes again upon after restart (to "always"). Would love this setting to stay in the way how I set it after docker restart.

Easy to reproduce. Just change the setting and restart docker. You will notice that it will change back.

Thanks for fixing!

**Comment by RandomNinjaAtk** [comment]
Disable the auto config option that adjusts it….
