### ISSUE TITLE
[FEATURE] - LIDARR - MusicBrainz support for music videos like in AMVD

### ISSUE THREAD

**Issue by nothing2obvi** [RandomNinjaAtk/arr-scripts#229]
**Is your feature request related to a problem? Please describe.**
I have run into a few problems downloading music videos:

1. IMVDB does not look through contributed videos often. It's been 3 weeks and they haven't looked at my submissions.

2. Lidarr is not updating my artists with the IMVDB links I've added to artist pages on MusicBrainz.

**Describe the solution you'd like**
A solution to this would be to get videos from MusicBrainz, like was done with AMVD. I seem to be able to add music videos to MusicBrainz without any voting required.

I also used AMVD in the past for some of these same artists, and AMVD downloaded many more music videos than the current arr-script does.

**Describe alternatives you've considered**
Obviously I could wait for IMVDB to take my submissions but at this rate it feels like they're not going to get to them at all. I've tried asking for support about Lidarr updating artists' links but I'm told it should just "happen." It doesn't seem to be happening.

**Comment by RandomNinjaAtk** [comment]
Can’t do that, unfortunately the musicbrainz website cannot handle the web traffic and had threatened the Lidarr project in the past because the scripts long ago would connect to it to do certain things… so the functionality had to be removed/scrapped for that reason.

The only way it could be implemented would be using a mirror and I’m not aware of any that exist. Or if lidarrs metadata mirror could pull in the extra data to facilitate it…. I’m doubtful that would happen though….

**Comment by nothing2obvi** [comment]
Thanks for your quick response. Oh, okay, I get that. When I was looking for MusicBrainz mirrors I found [this](https://musicbrainz.org/doc/MusicBrainz_Server). Could it potentially be an option?

**Comment by RandomNinjaAtk** [comment]
If you self hosted your own mirror, then possibly, it could be reincorporated. I just don’t think many would do that and I’d have to hack things back together to support it for a minority of users.

I used to run my own local mirror when LSIO had a container that could do it, but they depreciated it.

**Comment by nothing2obvi** [comment]
I just saw the requirements for running the mirror. I see how not many people would do it. Thanks for your time and effort.
