### ISSUE TITLE
[FEATURE] - Docker mods

### ISSUE THREAD

**Issue by PierreDurrr** [RandomNinjaAtk/arr-scripts#23]
Since the scripts are designed to be added to [Linuxserver.io](https://www.linuxserver.io/) containers, will you consider make them available as [mods](https://github.com/linuxserver/docker-mods/) ?

**Comment by RandomNinjaAtk** [comment]
I have no plans to work on it as a docker mod

**Comment by MARAllMighty** [comment]
Can you help the users of your scripts understand why you jumped from a much easier to use container structure into now manually adding and manually updating your scripts? Docker mods would make this a lot easier for many people to use and I'm struggling to see the benefits in jumping 3 times to new structures if the end result is harder to use, harder to maintain and harder to update.

**Comment by RandomNinjaAtk** [comment]
I honestly don't have to justify anything but for some of the reasons, you can find here:
https://github.com/RandomNinjaAtk/arr-scripts/issues/3#issuecomment-1629751218
