### ISSUE TITLE
Sonarr error

### ISSUE THREAD

**Issue by shedman214** [RandomNinjaAtk/arr-scripts#235]
I can't seem to get mine to work I keep getting an error on all my scripts. im getting erros for the arr's script for the dailytrimmer and extra bash script.
Logs: https://logpaste.com/lZDXeJr9

**Comment by RandomNinjaAtk** [comment]
Looks like the setup script did not run. Double check you followed the installation instructions correctly.

Reboot the container and watch the container logs to see if the setup script runs, which installs all the dependencies and etc.

**Comment by shedman214** [comment]
This is my config 
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/32603273/6ac39480-b0e8-4df5-90a5-251bd70b93e5)

**Comment by RandomNinjaAtk** [comment]
Again, please re-read the installation instructions and follow it to a T. The problems your having are caused by not following the installation instructions. The picture and logs you posted are evidence of that.

**Comment by shedman214** [comment]
I promise I have read the steps to the T and the only thing I can think of being bad is my folders setup. I use an unpaid server. could this be the culprit of my bad setup? 
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/32603273/727499d3-f3a3-49b7-8d98-e52f61a8d466)

**Comment by shedman214** [comment]
> Again, please re-read the installation instructions and follow it to a T. The problems you're having are caused by not following the installation instructions. The picture and logs you posted are evidence of that.

I got further this time as my functions file has a broken pipe as in the logs states. 

```
04/12/2024
11:52:58 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/functions: line 21: xq: command not found 
04/12/2024
11:52:58 AM
[Error] DailySeriesEpisodeTrimmer.bash: cat: write error: Broken pipe 
04/12/2024
11:52:58 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/functions: line 27: xq: command not found 
04/12/2024
11:52:58 AM
[Error] DailySeriesEpisodeTrimmer.bash: cat: write error: Broken pipe 
04/12/2024
11:52:58 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/functions: line 28: xq: command not found 
04/12/2024
11:52:58 AM
[Error] DailySeriesEpisodeTrimmer.bash: cat: write error: Broken pipe 
04/12/2024
11:52:58 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/functions: line 29: xq: command not found 
04/12/2024
11:52:58 AM
[Error] DailySeriesEpisodeTrimmer.bash: cat: write error: Broken pipe 
04/12/2024
11:52:58 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/DailySeriesEpisodeTrimmer.bash: line 50: [: !=: unary operator expected 
04/12/2024
11:52:58 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/DailySeriesEpisodeTrimmer.bash: line 56: [: !=: unary operator expected 
04/12/2024
11:52:58 AM
[Error] Extras.bash: /config/extended/functions: line 21: xq: command not found 
04/12/2024
11:52:58 AM
[Error] Extras.bash: cat: write error: Broken pipe 
04/12/2024
11:52:58 AM
[Error] Extras.bash: /config/extended/functions: line 27: xq: command not found 
04/12/2024
11:52:58 AM
[Error] Extras.bash: cat: write error: Broken pipe 
04/12/2024
11:52:58 AM
[Error] Extras.bash: /config/extended/functions: line 28: xq: command not found 
04/12/2024
11:52:58 AM
[Error] Extras.bash: cat: write error: Broken pipe 
04/12/2024
11:52:58 AM
[Error] Extras.bash: /config/extended/functions: line 29: xq: command not found 
04/12/2024
11:52:58 AM
[Error] Extras.bash: cat: write error: Broken pipe 
04/12/2024
11:52:58 AM
[Error] Extras.bash: jq: error (at <stdin>:0): Cannot iterate over null (null) 
04/12/2024
11:52:59 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/functions: line 21: xq: command not found 
04/12/2024
11:52:59 AM
[Error] DailySeriesEpisodeTrimmer.bash: cat: write error: Broken pipe 
04/12/2024
11:52:59 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/functions: line 27: xq: command not found 
04/12/2024
11:52:59 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/functions: line 28: xq: command not found 
04/12/2024
11:52:59 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/functions: line 29: xq: command not found 
04/12/2024
11:52:59 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/DailySeriesEpisodeTrimmer.bash: line 50: [: !=: unary operator expected 
04/12/2024
11:52:59 AM
[Error] DailySeriesEpisodeTrimmer.bash: /config/extended/DailySeriesEpisodeTrimmer.bash: line 56: [: !=: unary operator expected 
04/12/2024
11:52:59 AM
[Error] Extras.bash: /config/extended/functions: line 21: xq: command not found 
```

**Comment by RandomNinjaAtk** [comment]
The logs still indicate that the init script and setup script are not running, which installs all the dependencies. So it's still a problem following the installation instructions.

When you first start the container, watch the logs from unraid, if you don't see it downloading the scripts and installing the dependencies, that is your problem. Nothing to be done on this end though...

**Comment by shedman214** [comment]
I figured it out and got it working, but now I have a new issue. The scripts are filling up my docker images/containers storage. is there a method to move the scripts to not be on the docker and use my actual media folder for downloading?

**Comment by RandomNinjaAtk** [comment]
Shouldn't be possible because the /config folder should be mounted to your storage... Make sure configured the container properly.
