### ISSUE TITLE
[FEATURE] - Lidarr - Script activity duration/time

### ISSUE THREAD

**Issue by joelang1699** [RandomNinjaAtk/arr-scripts#238]
**Describe the solution you'd like**
Set script activity hours, eg run between hours of 0900-2300. This way my drives can spin down during night time for power saving.

**Describe alternatives you've considered**
Script shutting down Lidarr makes it unavailable for requests which I want to avoid.

**Comment by RandomNinjaAtk** [comment]
You could accomplish this via cron, just disable autorun and create a cron job to run them at a scheduled timeframe.

**Comment by joelang1699** [comment]
I'm unsure how I can set a cron job inside of the container?

**Comment by RandomNinjaAtk** [comment]
Actually you could not accomplish it via cron because the script will just sleep when not enabled. However, if you disable the video script, your drives should be able to sleep.... Because the video script is the only one messing with files in a final location...

**Comment by jaycedk** [comment]
Just had a idea.
The script runs on start, right ?
You can set the timeout ?
Set script interval to 24h.
Restart your docker at 2300 , do updates at 2300.
And its should only run after 2300, unless it takes over 24h to complete.

**Comment by RandomNinjaAtk** [comment]
I think @jaycedk idea is the best way to accomplish it. Otherwise something else would need to be created to start the process and kill the process after a certain time and that is not something I'm interested in developing or deploying...
