### ISSUE TITLE
[BUG] - Lidarr - Constantly trying to re-install miraclx/freyr-js

### ISSUE THREAD

**Issue by mat-pandaz** [RandomNinjaAtk/arr-scripts#244]
**Application**
Lidarr

**Host platform**
Unraid

**Script**
lidarr extended

**Describe the bug**

Constantly trying to redownload/instal freyr and other setup packages

**To Reproduce**

Install script
provided arl key
turned off beets in extended.conf (was erroring constantly) 

**Expected behavior**
once installed not try again

**Logs/Screenshots**
`Requirement already satisfied: jellyfish==0.10 in /usr/lib/python3.11/site-packages (0.10.0)
Requirement already satisfied: yt-dlp in /usr/lib/python3.11/site-packages (2024.4.9)
Requirement already satisfied: beets in /usr/lib/python3.11/site-packages (1.6.0)
Requirement already satisfied: yq in /usr/lib/python3.11/site-packages (3.4.1)
Requirement already satisfied: pyxDamerauLevenshtein in /usr/lib/python3.11/site-packages (1.7.1)
Requirement already satisfied: pyacoustid in /usr/lib/python3.11/site-packages (1.3.0)
Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: colorama in /usr/lib/python3.11/site-packages (0.4.6)
Requirement already satisfied: python-telegram-bot in /usr/lib/python3.11/site-packages (21.1.1)
Requirement already satisfied: pylast in /usr/lib/python3.11/site-packages (5.2.0)
Requirement already satisfied: mutagen in /usr/lib/python3.11/site-packages (1.47.0)
Requirement already satisfied: r128gain in /usr/lib/python3.11/site-packages (1.0.7)
Requirement already satisfied: tidal-dl in /usr/lib/python3.11/site-packages (2022.10.31.1)
Requirement already satisfied: deemix in /usr/lib/python3.11/site-packages (3.6.6)
Requirement already satisfied: brotli in /usr/lib/python3.11/site-packages (from yt-dlp) (1.1.0)
Requirement already satisfied: certifi in /usr/lib/python3.11/site-packages (from yt-dlp) (2024.2.2)
Requirement already satisfied: pycryptodomex in /usr/lib/python3.11/site-packages (from yt-dlp) (3.20.0)
Requirement already satisfied: urllib3<3,>=1.26.17 in /usr/lib/python3.11/site-packages (from yt-dlp) (2.2.1)
Requirement already satisfied: websockets>=12.0 in /usr/lib/python3.11/site-packages (from yt-dlp) (12.0)
Requirement already satisfied: unidecode in /usr/lib/python3.11/site-packages (from beets) (1.3.8)
Requirement already satisfied: musicbrainzngs>=0.4 in /usr/lib/python3.11/site-packages (from beets) (0.7.1)
Requirement already satisfied: pyyaml in /usr/lib/python3.11/site-packages (from beets) (6.0.1)
Requirement already satisfied: mediafile>=0.2.0 in /usr/lib/python3.11/site-packages (from beets) (0.12.0)
Requirement already satisfied: confuse>=1.0.0 in /usr/lib/python3.11/site-packages (from beets) (2.0.1)
Requirement already satisfied: munkres>=1.0.0 in /usr/lib/python3.11/site-packages (from beets) (1.1.4)
Requirement already satisfied: xmltodict>=0.11.0 in /usr/lib/python3.11/site-packages (from yq) (0.13.0)
Requirement already satisfied: tomlkit>=0.11.6 in /usr/lib/python3.11/site-packages (from yq) (0.12.4)
Requirement already satisfied: argcomplete>=1.8.1 in /usr/lib/python3.11/site-packages (from yq) (3.3.0)
Requirement already satisfied: audioread in /usr/lib/python3.11/site-packages (from pyacoustid) (3.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests) (3.7)
Requirement already satisfied: httpx~=0.27 in /usr/lib/python3.11/site-packages (from python-telegram-bot) (0.27.0)
Requirement already satisfied: crcmod>=1.7 in /usr/lib/python3.11/site-packages (from r128gain) (1.7)
Requirement already satisfied: ffmpeg-python~=0.2 in /usr/lib/python3.11/site-packages (from r128gain) (0.2.0)
Requirement already satisfied: tqdm>=4.28.1 in /usr/lib/python3.11/site-packages (from r128gain) (4.66.2)
Requirement already satisfied: aigpy>=2022.7.8.1 in /usr/lib/python3.11/site-packages (from tidal-dl) (2022.7.8.1)
Requirement already satisfied: pycryptodome in /usr/lib/python3.11/site-packages (from tidal-dl) (3.20.0)
Requirement already satisfied: pydub in /usr/lib/python3.11/site-packages (from tidal-dl) (0.25.1)
Requirement already satisfied: prettytable in /usr/lib/python3.11/site-packages (from tidal-dl) (3.10.0)
Requirement already satisfied: click in /usr/lib/python3.11/site-packages (from deemix) (8.1.7)
Requirement already satisfied: deezer-py>=1.3.0 in /usr/lib/python3.11/site-packages (from deemix) (1.3.7)
Requirement already satisfied: future in /usr/lib/python3.11/site-packages (from ffmpeg-python~=0.2->r128gain) (1.0.0)
Requirement already satisfied: anyio in /usr/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (4.3.0)
Requirement already satisfied: httpcore==1.* in /usr/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (1.0.5)
Requirement already satisfied: sniffio in /usr/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/lib/python3.11/site-packages (from httpcore==1.*->httpx~=0.27->python-telegram-bot) (0.14.0)
Requirement already satisfied: six>=1.9 in /usr/lib/python3.11/site-packages (from mediafile>=0.2.0->beets) (1.16.0)
Requirement already satisfied: wcwidth in /usr/lib/python3.11/site-packages (from prettytable->tidal-dl) (0.2.13)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
************ setup SMA ************
************ setup directory ************
************ download repo ************
fatal: destination path '/usr/local/sma' already exists and is not an empty directory.
Download QueueCleaner service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3783  100  3783    0     0  24710      0 --:--:-- --:--:-- --:--:-- 24888
Done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
Download AutoConfig service...
100 13063  100 13063    0     0  86946      0 --:--:-- --:--:-- --:--:-- 87671
Done
Download Video service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 35154  100 35154    0     0   211k      0 --:--:-- --:--:-- --:--:--  211k
Done
Download Tidal Video Downloader service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24160  100 24160    0     0   120k      0 --:--:-- --:--:-- --:--:--  120k
Done
Download Audio service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 84516  100 84516    0     0   486k      0 --:--:-- --:--:-- --:--:--  488k
Done
Download AutoArtistAdder service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15372  100 15372    0     0  97728      0 --:--:-- --:--:-- --:--:-- 97291
Done
Download UnmappedFilesCleaner service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1955  100  1955    0     0  13235      0 --:--:-- --:--:-- --:--:-- 13299
Done
Download ARLChecker service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18043  100 18043    0     0  94205      0 --:--:-- --:--:-- --:--:-- 94465
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   927  100   927    0     0   4907      0 --:--:-- --:--:-- --:--:--  4930
Done
Download Script Functions...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2243  100  2243    0     0  15221      0 --:--:-- --:--:-- --:--:-- 15258
Done
Download PlexNotify script...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2810  100  2810    0     0  19095      0 --:--:-- --:--:-- --:--:-- 19115
Done
Download SMA config...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4320  100  4320    0     0  17125      0 --:--:-- --:--:-- --:--:-- 17142
Done
Download Deemix config...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2232  100  2232    0     0  15277      0 --:--:-- --:--:-- --:--:-- 15393
Done
Download Tidal config...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   499  100   499    0     0   2649      0 --:--:-- --:--:-- --:--:--  2654
Done
Download LyricExtractor script...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3730  100  3730    0     0  24944      0 --:--:-- --:--:-- --:--:-- 25033
Done
Download ArtworkExtractor script...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2211  100  2211    0     0  14055      0 --:--:-- --:--:-- --:--:-- 14173
Done
Download Beets Tagger script...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3789  100  3789    0     0  21070      0 --:--:-- --:--:-- --:--:-- 21050
Done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
*** install packages ***
100  5790  100  5790    0     0  32762      0 --:--:-- --:--:-- --:--:-- 32897
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
OK: 508 MiB in 205 packages
*** install freyr client ***
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
OK: 508 MiB in 205 packages
npm WARN deprecated bin-version-check@6.0.0: Renamed to binary-version-check: https://www.npmjs.com/package/binary-version-check
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.

changed 312 packages in 35s

99 packages are looking for funding
  run `npm fund` for details
*** install python packages ***
Requirement already satisfied: jellyfish==0.10 in /usr/lib/python3.11/site-packages (0.10.0)
Requirement already satisfied: yt-dlp in /usr/lib/python3.11/site-packages (2024.4.9)
Requirement already satisfied: beets in /usr/lib/python3.11/site-packages (1.6.0)
Requirement already satisfied: yq in /usr/lib/python3.11/site-packages (3.4.1)
Requirement already satisfied: pyxDamerauLevenshtein in /usr/lib/python3.11/site-packages (1.7.1)
Requirement already satisfied: pyacoustid in /usr/lib/python3.11/site-packages (1.3.0)
Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: colorama in /usr/lib/python3.11/site-packages (0.4.6)
Requirement already satisfied: python-telegram-bot in /usr/lib/python3.11/site-packages (21.1.1)
Requirement already satisfied: pylast in /usr/lib/python3.11/site-packages (5.2.0)
Requirement already satisfied: mutagen in /usr/lib/python3.11/site-packages (1.47.0)
Requirement already satisfied: r128gain in /usr/lib/python3.11/site-packages (1.0.7)
Requirement already satisfied: tidal-dl in /usr/lib/python3.11/site-packages (2022.10.31.1)
Requirement already satisfied: deemix in /usr/lib/python3.11/site-packages (3.6.6)
Requirement already satisfied: brotli in /usr/lib/python3.11/site-packages (from yt-dlp) (1.1.0)
Requirement already satisfied: certifi in /usr/lib/python3.11/site-packages (from yt-dlp) (2024.2.2)
Requirement already satisfied: pycryptodomex in /usr/lib/python3.11/site-packages (from yt-dlp) (3.20.0)
Requirement already satisfied: urllib3<3,>=1.26.17 in /usr/lib/python3.11/site-packages (from yt-dlp) (2.2.1)
Requirement already satisfied: websockets>=12.0 in /usr/lib/python3.11/site-packages (from yt-dlp) (12.0)
Requirement already satisfied: unidecode in /usr/lib/python3.11/site-packages (from beets) (1.3.8)
Requirement already satisfied: musicbrainzngs>=0.4 in /usr/lib/python3.11/site-packages (from beets) (0.7.1)
Requirement already satisfied: pyyaml in /usr/lib/python3.11/site-packages (from beets) (6.0.1)
Requirement already satisfied: mediafile>=0.2.0 in /usr/lib/python3.11/site-packages (from beets) (0.12.0)
Requirement already satisfied: confuse>=1.0.0 in /usr/lib/python3.11/site-packages (from beets) (2.0.1)
Requirement already satisfied: munkres>=1.0.0 in /usr/lib/python3.11/site-packages (from beets) (1.1.4)
Requirement already satisfied: xmltodict>=0.11.0 in /usr/lib/python3.11/site-packages (from yq) (0.13.0)
Requirement already satisfied: tomlkit>=0.11.6 in /usr/lib/python3.11/site-packages (from yq) (0.12.4)
Requirement already satisfied: argcomplete>=1.8.1 in /usr/lib/python3.11/site-packages (from yq) (3.3.0)
Requirement already satisfied: audioread in /usr/lib/python3.11/site-packages (from pyacoustid) (3.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests) (3.7)
Requirement already satisfied: httpx~=0.27 in /usr/lib/python3.11/site-packages (from python-telegram-bot) (0.27.0)
Requirement already satisfied: crcmod>=1.7 in /usr/lib/python3.11/site-packages (from r128gain) (1.7)
Requirement already satisfied: ffmpeg-python~=0.2 in /usr/lib/python3.11/site-packages (from r128gain) (0.2.0)
Requirement already satisfied: tqdm>=4.28.1 in /usr/lib/python3.11/site-packages (from r128gain) (4.66.2)
Requirement already satisfied: aigpy>=2022.7.8.1 in /usr/lib/python3.11/site-packages (from tidal-dl) (2022.7.8.1)
Requirement already satisfied: pycryptodome in /usr/lib/python3.11/site-packages (from tidal-dl) (3.20.0)
Requirement already satisfied: pydub in /usr/lib/python3.11/site-packages (from tidal-dl) (0.25.1)
Requirement already satisfied: prettytable in /usr/lib/python3.11/site-packages (from tidal-dl) (3.10.0)
Requirement already satisfied: click in /usr/lib/python3.11/site-packages (from deemix) (8.1.7)
Requirement already satisfied: deezer-py>=1.3.0 in /usr/lib/python3.11/site-packages (from deemix) (1.3.7)
Requirement already satisfied: future in /usr/lib/python3.11/site-packages (from ffmpeg-python~=0.2->r128gain) (1.0.0)
Requirement already satisfied: anyio in /usr/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (4.3.0)
Requirement already satisfied: httpcore==1.* in /usr/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (1.0.5)
Requirement already satisfied: sniffio in /usr/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/lib/python3.11/site-packages (from httpcore==1.*->httpx~=0.27->python-telegram-bot) (0.14.0)
Requirement already satisfied: six>=1.9 in /usr/lib/python3.11/site-packages (from mediafile>=0.2.0->beets) (1.16.0)
Requirement already satisfied: wcwidth in /usr/lib/python3.11/site-packages (from prettytable->tidal-dl) (0.2.13)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
************ setup SMA ************
************ setup directory ************
************ download repo ************
fatal: destination path '/usr/local/sma' already exists and is not an empty directory.
Download QueueCleaner service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3783  100  3783    0     0  86652      0 --:--:-- --:--:-- --:--:-- 87976
Done
Download AutoConfig service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13063  100 13063    0     0   270k      0 --:--:-- --:--:-- --:--:--  277k
Done
Download Video service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 35154  100 35154    0     0   723k      0 --:--:-- --:--:-- --:--:--  730k
Done
Download Tidal Video Downloader service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24160  100 24160    0     0   501k      0 --:--:-- --:--:-- --:--:--  512k
Done
Download Audio service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 84516  100 84516    0     0  1355k      0 --:--:-- --:--:-- --:--:-- 1375k
Done
Download AutoArtistAdder service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15372  100 15372    0     0   323k      0 --:--:-- --:--:-- --:--:--  326k
Done
Download UnmappedFilesCleaner service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1955  100  1955    0     0  45920      0 --:--:-- --:--:-- --:--:-- 46547
Done
Download ARLChecker service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18043  100 18043    0     0   394k      0 --:--:-- --:--:-- --:--:--  400k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   927  100   927    0     0  20439      0 --:--:-- --:--:-- --:--:-- 20600
Done
Download Script Functions...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2243  100  2243    0     0  50854      0 --:--:-- --:--:-- --:--:-- 52162
Done
Download PlexNotify script...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2810  100  2810    0     0  59811      0 --:--:-- --:--:-- --:--:-- 61086
Done
Download SMA config...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4320  100  4320    0     0  93508      0 --:--:-- --:--:-- --:--:-- 96000
Done
Download Deemix config...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2232  100  2232    0     0  49818      0 --:--:-- --:--:-- --:--:-- 50727
Done
Download Tidal config...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   499  100   499    0     0  11271      0 --:--:-- --:--:-- --:--:-- 11340
Done
Download LyricExtractor script...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3730  100  3730    0     0  85521      0 --:--:-- --:--:-- --:--:-- 86744
Done
Download ArtworkExtractor script...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2211  100  2211    0     0  50432      0 --:--:-- --:--:-- --:--:-- 51418
Done
Download Beets Tagger script...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3789  100  3789    0     0  86522      0 --:--:-- --:--:-- --:--:-- 88116
Done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5790  100  5790    0     0   123k      0 --:--:-- --:--:-- --:--:--  125k
*** install packages ***
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
OK: 508 MiB in 205 packages
*** install freyr client ***
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
OK: 508 MiB in 205 packages
npm WARN deprecated bin-version-check@6.0.0: Renamed to binary-version-check: https://www.npmjs.com/package/binary-version-check
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.

changed 312 packages in 9s

99 packages are looking for funding
  run `npm fund` for details
*** install python packages ***
Requirement already satisfied: jellyfish==0.10 in /usr/lib/python3.11/site-packages (0.10.0)
Requirement already satisfied: yt-dlp in /usr/lib/python3.11/site-packages (2024.4.9)
Requirement already satisfied: beets in /usr/lib/python3.11/site-packages (1.6.0)
Requirement already satisfied: yq in /usr/lib/python3.11/site-packages (3.4.1)
Requirement already satisfied: pyxDamerauLevenshtein in /usr/lib/python3.11/site-packages (1.7.1)
Requirement already satisfied: pyacoustid in /usr/lib/python3.11/site-packages (1.3.0)
Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: colorama in /usr/lib/python3.11/site-packages (0.4.6)
Requirement already satisfied: python-telegram-bot in /usr/lib/python3.11/site-packages (21.1.1)
Requirement already satisfied: pylast in /usr/lib/python3.11/site-packages (5.2.0)
Requirement already satisfied: mutagen in /usr/lib/python3.11/site-packages (1.47.0)
Requirement already satisfied: r128gain in /usr/lib/python3.11/site-packages (1.0.7)
Requirement already satisfied: tidal-dl in /usr/lib/python3.11/site-packages (2022.10.31.1)
Requirement already satisfied: deemix in /usr/lib/python3.11/site-packages (3.6.6)
Requirement already satisfied: brotli in /usr/lib/python3.11/site-packages (from yt-dlp) (1.1.0)
Requirement already satisfied: certifi in /usr/lib/python3.11/site-packages (from yt-dlp) (2024.2.2)
Requirement already satisfied: pycryptodomex in /usr/lib/python3.11/site-packages (from yt-dlp) (3.20.0)
Requirement already satisfied: urllib3<3,>=1.26.17 in /usr/lib/python3.11/site-packages (from yt-dlp) (2.2.1)
Requirement already satisfied: websockets>=12.0 in /usr/lib/python3.11/site-packages (from yt-dlp) (12.0)
Requirement already satisfied: unidecode in /usr/lib/python3.11/site-packages (from beets) (1.3.8)
Requirement already satisfied: musicbrainzngs>=0.4 in /usr/lib/python3.11/site-packages (from beets) (0.7.1)
Requirement already satisfied: pyyaml in /usr/lib/python3.11/site-packages (from beets) (6.0.1)
Requirement already satisfied: mediafile>=0.2.0 in /usr/lib/python3.11/site-packages (from beets) (0.12.0)
Requirement already satisfied: confuse>=1.0.0 in /usr/lib/python3.11/site-packages (from beets) (2.0.1)
Requirement already satisfied: munkres>=1.0.0 in /usr/lib/python3.11/site-packages (from beets) (1.1.4)
Requirement already satisfied: xmltodict>=0.11.0 in /usr/lib/python3.11/site-packages (from yq) (0.13.0)
Requirement already satisfied: tomlkit>=0.11.6 in /usr/lib/python3.11/site-packages (from yq) (0.12.4)
Requirement already satisfied: argcomplete>=1.8.1 in /usr/lib/python3.11/site-packages (from yq) (3.3.0)
Requirement already satisfied: audioread in /usr/lib/python3.11/site-packages (from pyacoustid) (3.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests) (3.7)
Requirement already satisfied: httpx~=0.27 in /usr/lib/python3.11/site-packages (from python-telegram-bot) (0.27.0)
Requirement already satisfied: crcmod>=1.7 in /usr/lib/python3.11/site-packages (from r128gain) (1.7)
Requirement already satisfied: ffmpeg-python~=0.2 in /usr/lib/python3.11/site-packages (from r128gain) (0.2.0)
Requirement already satisfied: tqdm>=4.28.1 in /usr/lib/python3.11/site-packages (from r128gain) (4.66.2)
Requirement already satisfied: aigpy>=2022.7.8.1 in /usr/lib/python3.11/site-packages (from tidal-dl) (2022.7.8.1)
Requirement already satisfied: pycryptodome in /usr/lib/python3.11/site-packages (from tidal-dl) (3.20.0)
Requirement already satisfied: pydub in /usr/lib/python3.11/site-packages (from tidal-dl) (0.25.1)
Requirement already satisfied: prettytable in /usr/lib/python3.11/site-packages (from tidal-dl) (3.10.0)
Requirement already satisfied: click in /usr/lib/python3.11/site-packages (from deemix) (8.1.7)
Requirement already satisfied: deezer-py>=1.3.0 in /usr/lib/python3.11/site-packages (from deemix) (1.3.7)
Requirement already satisfied: future in /usr/lib/python3.11/site-packages (from ffmpeg-python~=0.2->r128gain) (1.0.0)
Requirement already satisfied: anyio in /usr/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (4.3.0)
Requirement already satisfied: httpcore==1.* in /usr/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (1.0.5)
Requirement already satisfied: sniffio in /usr/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/lib/python3.11/site-packages (from httpcore==1.*->httpx~=0.27->python-telegram-bot) (0.14.0)
Requirement already satisfied: six>=1.9 in /usr/lib/python3.11/site-packages (from mediafile>=0.2.0->beets) (1.16.0)
Requirement already satisfied: wcwidth in /usr/lib/python3.11/site-packages (from prettytable->tidal-dl) (0.2.13)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
************ setup SMA ************
************ setup directory ************
************ download repo ************
fatal: destination path '/usr/local/sma' already exists and is not an empty directory.
Download QueueCleaner service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3783  100  3783    0     0  79650      0 --:--:-- --:--:-- --:--:-- 80489
Done
Download AutoConfig service...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed`

**Additional context**

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by RandomNinjaAtk** [comment]
I'm making a guess, but it seems like you didn't follow the install instructions correctly and you most likely have the Init file in the wrong directory, which would cause it to have the behavior your experiencing.... 

Please re-read the installation instructions and verify that you have followed the correctly.

**Comment by mat-pandaz** [comment]
step 1 :
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/39424876/7bd125cb-13b6-4fea-905b-0340d459a5b6)

step 2 :
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/39424876/a51072a0-9c93-4e44-9ae1-884b9fc7de86)
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/39424876/d6d0d64c-0abb-4b76-8558-268eaf6eddce)

It worked fine last night after disabling beets, woke up this morning and it is looping on this (tried restarting etc).  

I found it works if I delete the '/usr/local/sma' folder, it will run once correctly and then revert back to the loop.

**Comment by mat-pandaz** [comment]
If I delete scripts_init.bash then it seems to run fine without rerunning it constantly.

**Comment by mat-pandaz** [comment]
Yup, my bad.  Had read and re-read and even thought I'd checked but seems I had my eyes on backwards.  Thanks!

**Comment by RandomNinjaAtk** [comment]
Glad you see the misconfiguration, however, I have a pushed a change that should prevent user misconfiguration issues going forward...
