### ISSUE TITLE
[USER-ERROR] - Sabnzbd - Error with setup.bash

### ISSUE THREAD

**Issue by mrmuiz** [RandomNinjaAtk/arr-scripts#247]
**Application**
SABnzbd

**Host platform**
Unraid/synology 

**Script**
setup.bash

**Script Version**
Please provide the script version number 1.8

**Describe the bug**
[custom-init] setup.bash: executing...

/custom-cont-init.d/setup.bash: line 7: syntax error near unexpected token `newline'

/custom-cont-init.d/setup.bash: line 7: `<!DOCTYPE html>'

[custom-init] setup.bash: exited 2

Is this a problem?

**Comment by RandomNinjaAtk** [comment]
Please post a full log from the container that shows the full startup. This is not reproducible, which seems to indicate that you may have incorrectly followed the instructions for the installation.

**Comment by RandomNinjaAtk** [comment]
Follow the installation instructions correctly and it will resolve your issue because this is not reproducible.

**Comment by mrmuiz** [comment]
> Follow the installation instructions correctly and it will resolve your issue because this is not reproducible.

Well almost a year later and the problem is still there. It just  fails. Thankfully i still have the old  init.bash file. And  that one works perfect.
I will put it in again to see the log this week.
