### ISSUE TITLE
[FEATURE] - Lidarr - Use beets tagging for Indexer Downloads

### ISSUE THREAD

**Issue by nevrion** [RandomNinjaAtk/arr-scripts#252]
Since Deezer doesn't find all albums (especially older ones) or all artists, I'm wondering if it's possible for your Beets script to be used to tag tracks that have been downloaded via the indexer?

**Comment by RandomNinjaAtk** [comment]
If you connect the beets tagger script as a connection in lidarr, it can run after every import...

**Comment by RandomNinjaAtk** [comment]
If you connect the beets tagger (BeetsTagger.bash) script as a connection in lidarr, it can run after every import...

Path: /config/extended/BeetsTagger.bash
