### ISSUE TITLE
[HELP] - Lidarr - NzbFolder: Folder does not exist 

### ISSUE THREAD

**Issue by BrandonG777** [RandomNinjaAtk/arr-scripts#256]
**Application**
Lidarr

**Host platform**
Unraid

**Script**
not sure, other than lidarr related. output all just goes to my container log and I know I'm seeing several different logs for the various scripts here.

**Script Version**
uhhh... lastest as of 5/11/2024

**Describe the bug**
I'm sure this is the result of me not setting this up correctly in relation to SABnzbd but I'm not sure what I've done wrong. Could someone give me some direction? 
2024-05-11 07:28:21 :: Audio :: 2.44 :: Adding download Client
[Warn] LidarrErrorPipeline: FluentValidation.ValidationException: Validation failed: 
 -- NzbFolder: Folder does not exist 
[v2.2.5.4141] FluentValidation.ValidationException: Validation failed: 
 -- NzbFolder: Folder does not exist

**To Reproduce**
importPath set to my SABnzbd music output folder in extended.conf, I think this is what broke it but I don't want downloads going into my appdata since this is backed up nightly and I have a dedicated temp drive for stuff like this.

**Expected behavior**
I'm not exactly sure what is happening at this point in the script, something is trying to hand off to SABnzbd but unsure why (I'm sure this is a REALLY good reason).

**Logs/Screenshots**
2024-05-11 07:28:21 :: Audio :: 2.44 :: Adding download Client
[Warn] LidarrErrorPipeline: FluentValidation.ValidationException: Validation failed: 
 -- NzbFolder: Folder does not exist 
[v2.2.5.4141] FluentValidation.ValidationException: Validation failed: 
 -- NzbFolder: Folder does not exist

**Additional context**
Music is successfully downloaded... but I'm sure my life is missing something cool as a result.

**Comment by RandomNinjaAtk** [comment]
You should not be mixing the two downloaders keep their import folders separate.

Just check that the black hole client is pointed to a folder for nzb and that will likely resolve it… keep in mind that the functionality isn’t actually used and the black hole client shouldn’t be used to process any nzb files… which is why it’s set to a lower priority.

**Comment by RandomNinjaAtk** [comment]
No response
