### ISSUE TITLE
[BUG] - arr-scripts - not all scripts work with non-standard ports

### ISSUE THREAD

**Issue by Jorman** [RandomNinjaAtk/arr-scripts#260]
Hi, thanks for this collection of scripts!

I would like to point out one thing that only affects some scripts, so not all, if you want you can extend the conversation and create a detailed report.
If applications use a non-standard port then some scripts will not work, this an example log from `Sonarr`
```
31/05/2024
00:13:08
2024-05-30 22:13:08 :: AutoConfig :: 1.8 :: Complete
31/05/2024
00:13:08
2024-05-30 22:13:08 :: AutoConfig :: 1.8 :: Updating Sonrr Media Management...
31/05/2024
00:13:08
2024-05-30 22:13:08 :: AutoConfig :: 1.8 :: Complete
31/05/2024
00:13:08
2024-05-30 22:13:08 :: AutoConfig :: 1.8 :: Updating Sonarr Medata Settings...
31/05/2024
00:13:08
2024-05-30 22:13:08 :: AutoConfig :: 1.8 :: Configuring Sonarr Custom Scripts
31/05/2024
00:13:08
2024-05-30 22:13:08 :: AutoConfig :: 1.8 :: PlexNotify.bash already added to Sonarr custom scripts
31/05/2024
00:13:08
2024-05-30 22:13:08 :: AutoConfig :: 1.8 :: Adding DailySeriesEpisodeTrimmer.bash to Sonarr custom scripts
31/05/2024
00:13:10
31/05/2024
00:13:10
===========================================
31/05/2024
00:13:10
Processing Sonarr Server: [instance1]
31/05/2024
00:13:10
===========================================
31/05/2024
00:13:10
31/05/2024
00:13:11
[ERR] Unable to obtain service version information
31/05/2024
00:13:11
[ERR] HTTP error: Call failed. Connection refused : GET http://REDACTED:8989/api/v3/system/status
31/05/2024
00:13:11
[ERR] Reason: Unable to determine. Please report this as a bug and attach your `verbose.log` file.
31/05/2024
00:13:11
2024-05-30 22:13:11 :: Recyclarr :: 1.8 :: Complete
31/05/2024
00:13:11
2024-05-30 22:13:11 :: Recyclarr :: 1.8 :: Script sleeping for 6h...
```
I noticed that in the function file, the port of use is extracted, as well as a lot of other information
arrPort="$(cat /config/config.xml | xq | jq -r .Config.Port)"
However, it is not reported in all scripts that are executed.

**Comment by RandomNinjaAtk** [comment]
Please provide a list of the scripts your having an issue with, most, if not all should work with whatever port you have set.

One culprit of not supporting custom ports is QueueCleaner, but I just pushed changes to that today that resolves that.... 

So if you cannot provide more detailed logs and which scripts need further investigation, I'm going to close this a resolved...

**Comment by Jorman** [comment]
Hi, sorry for the delay in replying, I'll do some testing these days and let you know if it's ok, I'll go ahead and update the script now.
From what I remember, I had to manually change the ports in multiple files.
I'll let you know as soon as I check, thanks.
Do you have any suggestions for testing all the scripts in one go? Maybe by enabling an extended log.
