### ISSUE TITLE
[BUG] - Lidarr - bypassing prowlarr tags for downloads

### ISSUE THREAD

**Issue by JFarq** [RandomNinjaAtk/arr-scripts#268]
**Application**
Lidarr/Transmission

**Host platform**
Unraid

**Describe the bug**
I have tags set up in Prowlarr, so Lidarr will not download from a torrent tracker that is for books only. Since using this script I'm torrenting bunch of tabs and 'learn this song' book from that tracker. 

I may be barking up the wrong tree here looking for the source of the problem, but I'm assuming correlation is causation, and the issue started when I installed the Lidarr scripts. I've read I don't know how many log files at this point trying to trace a specific torrent back to the source.

**Comment by RandomNinjaAtk** [comment]
These script do not manage or effect indexers and clients. So I think your looking in the wrong place....

Without any other evidence or logs to show that the scripts are causing it, not much can be done to look into it. The issue needs to be reproducible for it to have any hope of being resolved...

I think this is some sort of misconfiguration on your end that is causing it.

**Comment by RandomNinjaAtk** [comment]
No response, closing
