### ISSUE TITLE
[BUG] - Imvdb not working anymore, also tidal-media-downloader not working either

### ISSUE THREAD

**Issue by KarimAlaswad** [RandomNinjaAtk/arr-scripts#271]
Application
Lidarr
Host platform
Docker

Script
enableVideo

Script Version
most recent

Describe the bug
first time trying lidarr scripts to download music videos for my music library, but both ways don't work anymore. imvdb.com is down for a while now and  tidal-media-downloader gives me this error:
[ERR] DL Video[Blinding Lights] failed.Can't get the streamUrl, type is application/vnd.tidal.bts
i tried to change "apiKeyIndex": from 4 to 1 to try to fix that error, but it keeps reverting to 4 for some reason.

Logs/ScreenShots
![Screenshot 2024-06-11 051930](https://github.com/RandomNinjaAtk/arr-scripts/assets/102838480/6ee07206-8b9d-4b13-b71c-7ce60e7f813d)

![Screenshot 2024-06-11 052602](https://github.com/RandomNinjaAtk/arr-scripts/assets/102838480/329bf532-1fee-4bdb-a801-139a8b61ac5a)

**Comment by RandomNinjaAtk** [comment]
Both of these are upstream issues, not much to be done...

The only thing that can be done is maybe add some workarounds to allow disabling imvdb. As for the tidal client, you would need to do some manual testing and report the issue to the upstream project...

**Comment by RandomNinjaAtk** [comment]
No response, cannot reproduce
