### ISSUE TITLE
[BUG] - lidarr-extended - Can not add Artists

### ISSUE THREAD

**Issue by p5lukas** [RandomNinjaAtk/arr-scripts#272]
**Application**
Lidarr

**Host platform**
Unraid

**Script**
?

**Script Version**
?

**Describe the bug**
I can not add an artist...or dont know how. If i try to add an artist in lidarr, the log says, that this artist folder does not exist. The only way to add an artist is, to create the artist folder on my disk and search it then in lidarr. Is this normal? Shouldnt lidarr-extended be able to create the folder?

**To Reproduce**
see above

**Expected behavior**
Add a artist in lidarr, lidarr shoul create the artist folder and start to download.

**Logs/Screenshots**
![Screenshot 2024-06-14 151333](https://github.com/RandomNinjaAtk/arr-scripts/assets/134055235/37b2e8c1-612b-4da9-9c30-ded4d9c072ab)

**Additional context**
-

**Comment by p5lukas** [comment]
Nevermind. Added Artist in Lidarr will create an Artist Folder if you wait some time. Sorry.

**Comment by RandomNinjaAtk** [comment]
FYI: If it was an issue, it would have been an upstream issue...
