### ISSUE TITLE
[FEATURE] - LIDARR - Download Singles

### ISSUE THREAD

**Issue by t0fr** [RandomNinjaAtk/arr-scripts#278]
Perhaps I am just not able to find the option, but I'd like for the arr-scripts to automatically download singles.
There are many artists who only release singles and some often release singles months in advance of albums so I'd like to be able to download them once they are released.

Is there an option that I'm missing, or can it be added?

**Comment by hockeygoalie35** [comment]
Yeah that’s a LiDARR thing not these scripts. When you set it to download “future albums” or “all albums”, and ensure your profile includes singles, demos, etc, then it will queue singles to download.

**Comment by t0fr** [comment]
Hmmmmm. When I first set up Lidarr with the scripts, I was unmonitoring all the artists as there were many artists that I did not want it to bother with. However, it appeared to me that the scripts were downloading everything regardless of this setting.

Anyways, I've set it up now that I have multiple artists and tracks (both albums and singles) appearing in the "Wanted" tab and nothing seems to be happening. I may have borked my setup.

I think I'll try installing things from scratch because I'm not quite sure what I'm doing or how this works

**Comment by RandomNinjaAtk** [comment]
The scripts only do what lidarr tells it to do... So make sure your profile is correct as @hockeygoalie35 stated, if that doesn't provide the results your looking for, then you'll have to venture out of hear to the upstream project or musicbrainz....
