### ISSUE TITLE
[BUG] - RADARR - No module named 'guessit'

### ISSUE THREAD

**Issue by rav3ndk** [RandomNinjaAtk/arr-scripts#279]
**Application**
Radarr

**Host platform**
QNAP Container Station (Docker)

**Script**
AutoExtras

**Script Version**
1.5

**Describe the bug**
Trailer download stopped working. Can see in logs that trailers are downloaded, but then deleted again after getting this error:
File "/usr/local/sma/manual.py", line 5, in <module>
    import guessit
ModuleNotFoundError: No module named 'guessit'
2024-06-26 07:55:26 :: Extras :: 1.2 :: <movie title> :: 1 of 4 :: Trailer :: Sneak Peek “Chapters” Trailer :: ERROR :: SMA Processing Error

**To Reproduce**
1. Restart Container
2. Navigate to Logs
3. See trailer downloads failed because of above error

**Expected behavior**
Expected trailer to be downloaded and stored in movie folder

**Comment by RandomNinjaAtk** [comment]
Looks like the qtfaststart pip package is broken and won't install which is preventing the other packages from being installed.... Not really sure what to do about it...

**Comment by rav3ndk** [comment]
Don't know about qtfaststart pip package as it's not really something I've come across. To me it looks like issue with the SMA.

I did further testing myself to see if I could find a workaround since I am only using the scripts to download trailers, so I found a quick and dirty workaround. :)

I did the following inside the container as workaround - Delete lines with references to modules not installed after latest update:

- /usr/local/sma/manual.py - line 5 - import guessit
- /usr/local/sma/manual.py - line 13 - import tmdbssimple as tmdb
- /usr/local/sma/manual.py - line 415 - log.info(“Guessit version: %s.” % guessit.__version__)
- /usr/local/sma/resources/metadata.py - line 8 - import tmdbsimple as tmdb
- /usr/local/sma/resources/lang.py - line 1 - from babelfish import Language

This allowed the script to download and keep the trailer - but of course not a proper solution. But it will work for me until you can solve the SMA package issues.

**Comment by RandomNinjaAtk** [comment]
The problem is its a requirement for the SMA project, and when the installation attempts to install the SMA requirements, it fails because the package is broken, thus the other packages, guessit is not installed because of that single broken package...

If you comment out the qtfaststart package from the requirements.txt file and run it, it will install the remaining packages and work as intended after... Hence why I opened an issue with the SMA project...

**Comment by rav3ndk** [comment]
Missing the part about your ticket initially. But good find and it definitely sound like the correct fix would be to have the requirements.txt centrally corrected.

Just for my testing purposes. So, if I remove the line qtfaststart from /usr/local/sma/setup/requirements.txt and the run the requirements again, it should also work. Do I run requirements again using:
pip install -r setup/requirements.txt 
And should I be in directory /usr/local/sma when running it?

Also curious - would a restart of the Container then re-download requirements.txt again and then I have same issue again?

**Comment by RandomNinjaAtk** [comment]
As long as you don't do a full image update, it shouldn't reinstall even when it attempts to on container reboot.... 

The command would be from container cli: `pip3 install --break-system-packages -r /usr/local/sma/setup/requirements.txt`

After you modified/commented out the line. I might push some a workaround soon, but was hoping to hear back from the upstream project before resorting to that... Its a package that is only used if certain setting is enabled and the output file type is MP4, which is not something I use...

**Comment by hockeygoalie35** [comment]
It’s pretty funny that the actual issue is the ReadME isn’t found…

`KeyError: "linkname 'qtfaststart-1.8/README.rst' not found" `

**Comment by RandomNinjaAtk** [comment]
@hockeygoalie35 Yarp

@rav3ndk 
I did push a change to each arr app as a workaround, that should resolve it as long as the user isn't using the feature that requires it... 

Simply restarting each container should resolve it...

**Comment by RandomNinjaAtk** [comment]
This is resolved
#283
