### ISSUE TITLE
[BUG] - lidarr - npm warn deprecated

### ISSUE THREAD

**Issue by Jutsch** [RandomNinjaAtk/arr-scripts#286]
**Application**
Lidarr

**Host platform**
Ubuntu 24.04 - docker

**Script**
lidarr-scripts

**Script Version**
v2.0

**Describe the bug**
Docker-Log give four warnings: "npm warn deprecated"
npm warn deprecated bin-version-check@6.0.0: Renamed to binary-version-check: https://www.npmjs.com/package/binary-version-check
npm warn deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated superagent@6.1.0: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net

**To Reproduce**
1. Start container

**Expected behavior**
Install the newest versions

**Logs/Screenshots**
npm warn deprecated bin-version-check@6.0.0: Renamed to binary-version-check: https://www.npmjs.com/package/binary-version-check
npm warn deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated superagent@6.1.0: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net

**Additional context**

**NOTE**

**Comment by RandomNinjaAtk** [comment]
Looks/sounds like an upstream problem, because the packages come from the distro the container is built on (alpine)... If its not causing any errors with the scripts, then I guess ignore it and report the problem upstream, because that is out of scope here...

**Comment by Jutsch** [comment]
ah, okay, sorry, I'm not that good with this - then I will post this at the lidarr-github. Sorry, for wasting your time.

**Comment by RandomNinjaAtk** [comment]
@Jutsch I don't believe that is likely the appropriate place to post an issue, its more of alpine linux issue...

If everything is working, its probably best to just ignore it, if something is not working. Please provide detail as to which script is not working with log data. Otherwise I will proceed with closure.

**Comment by RandomNinjaAtk** [comment]
I'm not seeing any direct issues, closing
