### ISSUE TITLE
Migrate from old containers...

### ISSUE THREAD

**Issue by mason-xx** [RandomNinjaAtk/arr-scripts#29]
Did anybody switched successfully from the old containers to the linux.io ones? I'm currently a little lost do to that, since this was working very well for me and I don't what to fuck up my setup. Also I would prevent from starting from scratch... so any migration info would be helpfull. Thanks!

**Comment by RandomNinjaAtk** [comment]
https://github.com/RandomNinjaAtk/arr-scripts/issues/26#issuecomment-1641009373

**Comment by RandomNinjaAtk** [comment]
Let me know if that resolves it. Making a backup of your config directory could be a smart move, because if anything goes wrong, you can restore from the backup.

**Comment by mason-xx** [comment]
Thanks for the hint.. will give it a shot. (I always backup ;))
