### ISSUE TITLE
[.extension filter] - Radarr/Sonarr - Is there a way to prevent subtitle .vtt filters from downloading for trailers specifically.?

### ISSUE THREAD

**Issue by nc88keyz** [RandomNinjaAtk/arr-scripts#299]
**Is your feature request related to a problem? Please describe.**
.vtt (subtitle files) are downloading for trailers. 

**Describe the solution you'd like**
filter flag in config fle

**Describe alternatives you've considered**
searching for *-trailer.vtt* files, It replaces them on each script refresh 

**Additional context**

**Comment by RandomNinjaAtk** [comment]
These should be embedded in the file and not external at all…  

I’ll check my setup but I’m fairly certain I don’t have any locally…. I believe yt-dlp downloads them to embed but they should be gone after they’re embedded… so you most likely have some other issue that is on your end only…

**Comment by nc88keyz** [comment]
I will be interested in your findings. I am not seeing any anomolies in the log file, permissions seems to be fine for every other container i am running. I know Radarr hates bdmv folders and iso files vs mkv mp4 but i am seeing it in various mounts.  I am also not seeing it in another python script that is pulling trailers using yt-dlp as well. If there is anything i can send you let me know.

**Comment by RandomNinjaAtk** [comment]
This should be resolved with the latest changes, it will not however cleanup existing files. I would recommend that you use something like this to cleanup the files: 
`find root/path/to/folder -type f -iname "*.vtt" -delete`
