### ISSUE TITLE
[BUG] - Lidarr - "command not found" on script run

### ISSUE THREAD

**Issue by sage2050** [RandomNinjaAtk/arr-scripts#30]
**Application**
Lidarr

**Script**
scripts_init.bash

**Script Version**
latest from lidarr install page

**Describe the bug**
lidarr container starts (lsio container, on UnRAID)

[custom-init] Files found, executing
[custom-init] scripts_init.bash: executing...
/custom-cont-init.d/scripts_init.bash: line 1: payload:allShortcutsEnabled:false: command not found
[custom-init] scripts_init.bash: exited 127
[Info] Bootstrap: Starting Lidarr - /app/lidarr

**To Reproduce**
happens every time lidarr container starts

**Expected behavior**
script installs extension

**Additional context**
volume mappings are as follows

/config -> /mnt/user/appdata/lidarr
/custom-services.d -> /mnt/user/appdata/lidarr/cs/custom-services.d
/custom-cont-init.d -> /mnt/user/appdata/lidarr/cci/custom-cont-init.d

**Comment by sage2050** [comment]
as you predicted it was human error 👍 

right-click save as on the scripts_init.bash link on the install page downloads a file full of json
navigating to the scripts_init.bash file and downloading it using the github UI grabbed the correct file. Copy/pasting the contents of the scripts_init.bash page on github also did not work for some reason.

marked closed

**Comment by RandomNinjaAtk** [comment]
Yeah, you can right click and save from the GitHub page, but you have to do it using the RAW link to get the actual file. Glad you were able to figure it out.

**Comment by tinng81** [comment]
I too have to admit made the same mistake, for everyone else struggling.

https://raw.githubusercontent.com/RandomNinjaAtk/arr-scripts/main/sonarr/scripts_init.bash

**Comment by captainnapalm** [comment]
Using the link in the instructions with wget also resulted in a huge file full of json. Replaced contents with that of scripts_init.bash and it is now working.
