### ISSUE TITLE
Using non standard ports because those ports were already taken in my setup.

### ISSUE THREAD

**Issue by Glynax** [RandomNinjaAtk/arr-scripts#31]
Alright I think I see where it's breaking, my readarrs are using port 9090 and 9191 because the expected ports were already in use by something else

`verifyApiAccess () {
  until false
  do
    arrApiTest=""
    arrApiVersion=""
    if [ "$arrPort" == "8989" ] || [ "$arrPort" == "7878" ]; then
      arrApiVersion="v3"
    elif [ "$arrPort" == "8686" ] || [ "$arrPort" == "8787" ]; then
      arrApiVersion="v1"
    fi
    arrApiTest=$(curl -s "$arrUrl/api/$arrApiVersion/system/status?apikey=$arrApiKey" | jq -r .instanceName)
    if [ "$arrApiTest" == "$arrName" ]; then
      break
    else
      log "$arrName is not ready, sleeping until valid response..."
      sleep 1
    fi
  done
}
`

_Originally posted by @Glynax in https://github.com/RandomNinjaAtk/arr-scripts/issues/22#issuecomment-1639239577_

**Comment by RandomNinjaAtk** [comment]
Since this is designed for docker, you shouldn’t be changing the softwares ports. You should just be adjusting the docker port mapping to change the port, which doesn’t break functionality.

**Comment by RandomNinjaAtk** [comment]
If you post your docker run/compose sample, can give you some edits to what you should be adjusting

**Comment by Glynax** [comment]
> If you post your docker run/compose sample, can give you some edits to show you what you should be adjusting

I almost get what you mean, but I'm never sure which is which in the compose is what, is the left the out of container port or the inside of container port?

---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - enableAutoConfig=true
      - enableQueueCleaner=true
      - plexUrl=http://192.
      - plexToken=gU
    volumes:
      - /opt/readarr-extended/data:/config
      - /media/nfs/Quartet/Plex/Audiobooks/:/books #optional
      - /media/nfs/Quartet/Plex/Sab/:/downloads #optional
      - /media/nfs/Quartet/Plex/transmission:/transmission
      - /opt/readarr-extended/custom-services.d:/custom-services.d
      - /opt/readarr-extended/custom-cont-init.d:/custom-cont-init.d
    ports:
      - 9090:9090
    restart: unless-stopped

  readarr2:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr2
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Detroit
      - enableAutoConfig=true
      - enableQueueCleaner=true
      - plexUrl=http://192.
      - plexToken=gUj

    volumes:
      - /opt/readarr-extended/data2:/config
      - /media/nfs/Quartet/Plex/Ebooks/Sorted/:/books #optional
      - /media/nfs/Quartet/Plex/Sab/:/downloads #optional
      - /media/nfs/Quartet/Plex/transmission:/transmission
      - /opt/readarr-extended/custom-services.d:/custom-services.d
      - /opt/readarr-extended/custom-cont-init.d:/custom-cont-init.d

    ports:
      - 9191:9191
    restart: unless-stopped

**Comment by RandomNinjaAtk** [comment]
Always best to read the providers documentation:
Example: https://docs.linuxserver.io/images/docker-lidarr#parameters

So based on y our config, I believe it should look like this:
Top:
```
ports:
  - 9090:8787
```
Bottom:
```
ports:
  - 9191:8787
```

**Comment by Glynax** [comment]
Yeah that worked, thanks :)
