### ISSUE TITLE
[BUG] - sabnzbd - Script not running

### ISSUE THREAD

**Issue by steve1977** [RandomNinjaAtk/arr-scripts#32]
Created a new container and manually added the folder and paths. Unfortunately, the script doens't run at start. Maybe a permission issue? Error message from docker log below:

[custom-init] Files found, executing
[custom-init] scripts_init.bash: executing...
[custom-init] scripts_init.bash: exited 2

Also, a question about future updates: Are the scripts themselves updated automatically once installed? The description on your web-site implies that only the "extended.conf" needs to be manually updated if it changes (which hopefully won't happen)?

**Comment by RandomNinjaAtk** [comment]
This is a user error of some sort…. Nothing to triage, make sure you downloaded the file correctly and etc…

**Comment by steve1977** [comment]
Thanks, yes, tried again and it is now working.

Also, a question about future updates: Are the scripts themselves updated automatically once installed? The description on your web-site implies that only the "extended.conf" needs to be manually updated if it changes (which hopefully won't happen)?

**Comment by RandomNinjaAtk** [comment]
Scripts update automatically but it’s not possible to auto update the config file without overwriting your settings, so if a new setting is added for a new feature, you may need to update it manually, same as the old containers, by adding new variables and etc. idk of any other way to improve it…
