### ISSUE TITLE
Sonarr - Issue with migration

### ISSUE THREAD

**Issue by steve1977** [RandomNinjaAtk/arr-scripts#34]
I successfully migrated Radarr, but struggling with the migration of Sonarr.

I copied config.xml and the five sonarr-db files and variants.

When starting up, I don't get to the UI, but see the folliwing error message(s):

*** SQL logic error no such column: t0.LanguageProfileId

**Comment by justinglock40** [comment]
What version of Sonarr did you come from?

**Comment by justinglock40** [comment]
The better way would be to clear your NEW folder and start up sonarr brand new, then use the backup files from your OLD sonarr instance to get you information moved over

**Comment by RandomNinjaAtk** [comment]
If your migrating, you need to use V4 sonarr, which is the develop tag.
