### ISSUE TITLE
PlexNotifier

### ISSUE THREAD

**Issue by justinglock40** [RandomNinjaAtk/arr-scripts#4]
Hey, so I added the script to the LSIO container and hardcoded the plexUrl and plexToken scripts into the script, but it still does not trigger the scan. Can you advise me on where I'm going wrong?

**Comment by RandomNinjaAtk** [comment]
Check your logs, without log data, there is no way of knowing.

**Comment by justinglock40** [comment]
I can see that it attempts to run the script, but can't seem to connect to plex for some reason. The same variables worked previously with your containers

<img width="810" alt="image" src="https://github.com/RandomNinjaAtk/arr-scripts/assets/23133649/43ae1267-532f-4fdd-9b2c-7f63e3befb9c">

**Comment by justinglock40** [comment]
it just repeats that over and over each time something triggers an event

**Comment by RandomNinjaAtk** [comment]
You have all the required packages installed?

If you do, try getting a new token and use that. If that doesn't work, then might be some other issue.

It works in my sonarr configuration, haven't fully tested the other apps yet.

**Comment by justinglock40** [comment]
I'm testing in Sonarr as well right now. I'm not sure if I have all the required packages installed do you have them listed anywhere by chance

**Comment by justinglock40** [comment]
So if I run this line manually

<img width="332" alt="image" src="https://github.com/RandomNinjaAtk/arr-scripts/assets/23133649/fa0a5e7a-56d5-42c6-9b14-50167a7b9d91">

I get 401 unauthorized, but if I run this line manually using the same IP and token:

<img width="451" alt="image" src="https://github.com/RandomNinjaAtk/arr-scripts/assets/23133649/5908b96b-c035-43f9-ab68-d6633f99dd75">


It returns the library section like it should

**Comment by justinglock40** [comment]
So made some progress. When I run both commands manually now it will return the correct values, but the script still fails with the same information

**Comment by justinglock40** [comment]
Found the issue. It seems everything is erroring out because of the xq package. It's not available on Alpine Linux. Do you know what I can do to fix this.

I tried substituting it for yq and jq, but it still doesn't work.

<img width="992" alt="image" src="https://github.com/RandomNinjaAtk/arr-scripts/assets/23133649/15f2be1a-60bc-4681-9e81-c24973b440a7">

**Comment by RandomNinjaAtk** [comment]
The package is installed but the setup scripts, so it sounds like you didn't use it, which is why it's not working

**Comment by justinglock40** [comment]
Evening,

Got it all working. You mention of the setup script was were I was going wrong., but I have both Radarr and Sonarr, running the Notifier script correctly now. 

Thanks for keeping a method to use this available

**Comment by RandomNinjaAtk** [comment]
Np

**Comment by RandomNinjaAtk** [comment]
When you have a chance, take a look at the latest docs:
https://github.com/RandomNinjaAtk/arr-scripts/tree/main/radarr#readme
https://github.com/RandomNinjaAtk/arr-scripts/tree/main/sonarr#readme
https://github.com/RandomNinjaAtk/arr-scripts/tree/main/sabnzbd#readme

It should solve your problem going forward...

**Comment by RandomNinjaAtk** [comment]
Also: https://github.com/RandomNinjaAtk/arr-scripts/tree/main#arr-scripts

**Comment by justinglock40** [comment]
Nice! Thank you for this!

**Comment by justinglock40** [comment]
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/23133649/5275d275-4fc8-421b-adb4-6897d2835ec2)

**Comment by RandomNinjaAtk** [comment]
This is user-error, please re-read and follow the setup instructions...

**Comment by justinglock40** [comment]
So it's hard to catch but on a fresh radarr deploy there's an error that happens with SMA stuff, but I can't catch it because it happens to fast. If I take the setup.bash script and comment out everything related to SMA. 

I don't get the errors with xq. Any thoughts on that?

**Comment by RandomNinjaAtk** [comment]
Your problem is the setup script isn't running, which is what installs the required packages. Which indicates a problem with following the install/setup instructions....
