### ISSUE TITLE
[FEATURE] Sonarr/Radarr - naming.json - Allow file to be modified and saved upon restart.

### ISSUE THREAD

**Issue by Repooc** [RandomNinjaAtk/arr-scripts#42]
**Is your feature request related to a problem? Please describe.**
I was trying to make the auto config for naming.json to use the plex format when altering naming.json or AutoConfig so i could use plex entry, the files get redownload upon restarting the docker container.

**Describe the solution you'd like**
A couple solutions could include:
1. Alter setup.bash to check if naming.json is there and if not, download it, if so, skip it
2. Alter AutoConfig.service file where it checks if /config/extended/naming.json is there or not to first check if /config/extended/custom-naming.json is there and then fall back to the original so a user can have custom-naming.json with their settings.

**Describe alternatives you've considered**
I considered forking and making needed changes for myself

**Comment by RandomNinjaAtk** [comment]
FYI: the default naming is completely compatible with Plex and other media services.

i can look at making it configurable. But like I said, the current included naming works with all of the media server based apps.

**Comment by RandomNinjaAtk** [comment]
Went with option 1, again the built in naming should already be optimized for plex/emby/jellyfin without any changes, its what I use....

This should now be resolved
