### ISSUE TITLE
[FEATURE] - Ability to configure AutoArtistAdder's imports into Lidarr

### ISSUE THREAD

**Issue by HA-Roberto** [RandomNinjaAtk/arr-scripts#46]
**Is your feature request related to a problem? Please describe.**
AutoArtistAdder is great to discover new music but id like to be able to have some customization options when adding the artist into Lidarr. 

**Describe the solution you'd like**
Ability to 
- tag the imported artists.
- only monitor Albums/EPs/Singles/All depending on a config setting

**Describe alternatives you've considered**
I am looking into the script and Lidarr API but I am not very technical so I am hoping to figure it out but realistically may just keep my fingers crossed until someone can help me.

**Additional context**

**Comment by RandomNinjaAtk** [comment]
I don’t see a way to tag and monitoring album/single/ep types is based on the existing settings, which you can already control…

So doesn’t look like there is anything to be done other than figure out if a tag could be added…

**Comment by RandomNinjaAtk** [comment]
Since album types is already easily configurable via lidarr settings, nothing to do.
Supporting tags looks to be possibly but not easily implementable, so I'm not going to bother with it. I will welcome a PR from someone who wants to get that to work, but I'm not going to work on it.
