### ISSUE TITLE
[BUG] - APP NAME - ISSUE TITLE

### ISSUE THREAD

**Issue by asdproton** [RandomNinjaAtk/arr-scripts#50]
**Application**
Sonarr

**Script**
I suspect: Autoconfigure

**Script Version**
Latest via Docker

**Describe the bug**
I noticed that media management uses Folder type "Season 00" where I prefer "Season 0". Moreover the rescan on refresh option is disabled. I changed these settings, hit save and all works as expected. However after a restart of the docker (where then all arr scripts are rerun/reinstalled) these settings are reverted...

I can currently only suspect that this has to do with auto configure script.

**Comment by RandomNinjaAtk** [comment]
If you already autoconfigured, you can just disable it the script....

**Comment by asdproton** [comment]
Understood. Is this mentioned somewhere in the docs and I was just too stupid to see? If not, maybe worth mentioning.
