### ISSUE TITLE
[BUG] - Album not downloading Tidal-DL

### ISSUE THREAD

**Issue by Breakingx** [RandomNinjaAtk/arr-scripts#53]
**Application**
Lidarr

**Script**
Tidal-dl

**Script Version**
2022.10.31.1

**Describe the bug**
Album not downloading

**To Reproduce**
1. Add "Asking Alexandria" as artist
2. Album "See What’s on the Inside" not downloading

**Additional context**
Just a quick question. Some albums aren't being downloaded but they are available on Tidal. For a example please look above. Some more examples are "10 Jahre Alligatoah" by Alligatoah, "Hartgeld im Club" by Callejon. Is there something I can tweak inside the tidal-dl settings?

Furthermore: What is the Multi-Thread-Download in the settings in tidal-dl I can't find something to that point in the documentary.

Best regards!

**Comment by RandomNinjaAtk** [comment]
Provide logs.

**Comment by RandomNinjaAtk** [comment]
No logs, closing…
