### ISSUE TITLE
Sonarr doesn't download trailer

### ISSUE THREAD

**Issue by memnos** [RandomNinjaAtk/arr-scripts#56]
**Application**
Sonarr

**Script**
Extras

**Script Version**
1.0.3/1.5

**Describe the bug**
Script doesn't download any trailer.
In log, for all the series whch as got trailers available of TMDB, i see this in log file:
2023-08-11 13:13:34 :: Extras :: 1.5 :: Special Ops: Lioness :: Cookies File Not Found!
2023-08-11 13:13:34 :: Extras :: 1.5 :: Special Ops: Lioness :: Searching for "it-IT" extras...
2023-08-11 13:13:34 :: Extras :: 1.5 :: Special Ops: Lioness :: 1 Extras Found!
2023-08-11 13:13:35 :: Extras :: 1.5 :: Special Ops: Lioness :: 1 of 1 :: Trailer :: Operazione Speciale: Lioness | Trailer Ufficiale ITA - Paramount+ (HywB_NgBWoU) :: Downloading (yt-dlp :: )...
2023-08-11 13:13:37 :: Extras :: 1.5 :: Special Ops: Lioness :: 1 of 1 :: Trailer :: Operazione Speciale: Lioness | Trailer Ufficiale ITA - Paramount+ (HywB_NgBWoU) :: ERROR :: Download Failed
2023-08-11 13:13:37 :: Extras :: 1.5 :: Special Ops: Lioness :: Marking/logging as Extras downloads complete (/config/extended/logs/extras/113962)

**To Reproduce**
Just restart docker

**Expected behavior**
It should download trailer, but it doesn't

**Logs/Screenshots**
https://pastebin.com/4AnSxfqm

**Additional context**
I don't know if it is downloader problem

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by RandomNinjaAtk** [comment]
There can be a number of causes for this, but in some cases, nothing can be done... The log file unfortunanelty doesn't capture the YT-DLP process which would give you more insight to what is going on... Generally, these are the causes:

1. Trailer is not actually available
2. The yt-dlp is requesting a format that is not available (default setting requires 720p video quality minimum
3. Trailer is Explicit, requires cookies.txt

I don't believe there is anything I can do to improve it, other than improving the logging output to show it. You have the ability to lower the video format restriction in the config file, if you arn't using cookies.txt, you should add that to: `/config/cookies.txt` (see yt-dlp documentation for how to create)

**Comment by RandomNinjaAtk** [comment]
If you update to the latest version, you should hopefully be able to see the yt-dlp process in the log file, then you can post a new logs here for further investigation.

**Comment by memnos** [comment]
Here is the new log, can you understand what is it?

2023-08-12 08:47:25 :: Extras :: 1.9 :: A Spy Among Friends :: Cookies File Not Found!
2023-08-12 08:47:25 :: Extras :: 1.9 :: A Spy Among Friends :: Searching for "it-IT" extras...
2023-08-12 08:47:25 :: Extras :: 1.9 :: A Spy Among Friends :: 1 Extras Found!
2023-08-12 08:47:25 :: Extras :: 1.9 :: A Spy Among Friends :: 1 of 1 :: Trailer :: Una spia tra noi | Nuova serie | Trailer (uu0lSZaImIs) :: Downloading (yt-dlp :: )...
[youtube] Extracting URL: https://www.youtube.com/watch?v=uu0lSZaImIs
[youtube] uu0lSZaImIs: Downloading webpage
[youtube] uu0lSZaImIs: Downloading ios player API JSON
[youtube] uu0lSZaImIs: Downloading android player API JSON
[youtube] uu0lSZaImIs: Downloading m3u8 information
ERROR: [youtube] uu0lSZaImIs: Requested format is not available. Use --list-formats for a list of available formats
2023-08-12 08:47:27 :: Extras :: 1.9 :: A Spy Among Friends :: 1 of 1 :: Trailer :: Una spia tra noi | Nuova serie | Trailer (uu0lSZaImIs) :: ERROR :: Download Failed
2023-08-12 08:47:27 :: Extras :: 1.9 :: A Spy Among Friends :: Marking/logging as Extras downloads complete (/config/extended/logs/extras/138624)

**Comment by RandomNinjaAtk** [comment]
You can see where it says requested format is not available, so script is working as designed. You can consider adjusting the default yt-dlp Selection setting to make it more permissive, in the extended.cof file.

anyways, there is nothing to be done…

**Comment by memnos** [comment]
Could you please suggest me a more permissive setting?
I really don't know what to put there.

It is the same setting it is in radarr where it works.
When i used sonarr-extended old version before to pass to arr-script it worked fine for me.
Tnx

**Comment by RandomNinjaAtk** [comment]
See this change: https://github.com/RandomNinjaAtk/arr-scripts/commit/ba74f4234ffb1867dde5de86605abe54c0d86e1d

**Comment by memnos** [comment]
I tried with this new settings but the error is the same.
To apply setting is it enough to change it in extended.conf and restart docker?

2023-08-12 12:58:49 :: Extras :: 1.9 :: A Spy Among Friends :: Cookies File Not Found!
2023-08-12 12:58:49 :: Extras :: 1.9 :: A Spy Among Friends :: Searching for "it-IT" extras...
2023-08-12 12:58:49 :: Extras :: 1.9 :: A Spy Among Friends :: 1 Extras Found!
2023-08-12 12:58:49 :: Extras :: 1.9 :: A Spy Among Friends :: 1 of 1 :: Trailer :: Una spia tra noi | Nuova serie | Trailer (uu0lSZaImIs) :: Downloading (yt-dlp :: )...
[youtube] Extracting URL: https://www.youtube.com/watch?v=uu0lSZaImIs
[youtube] uu0lSZaImIs: Downloading webpage
[youtube] uu0lSZaImIs: Downloading ios player API JSON
[youtube] uu0lSZaImIs: Downloading android player API JSON
[youtube] uu0lSZaImIs: Downloading m3u8 information
ERROR: [youtube] uu0lSZaImIs: Requested format is not available. Use --list-formats for a list of available formats
2023-08-12 12:58:51 :: Extras :: 1.9 :: A Spy Among Friends :: 1 of 1 :: Trailer :: Una spia tra noi | Nuova serie | Trailer (uu0lSZaImIs) :: ERROR :: Download Failed
2023-08-12 12:58:51 :: Extras :: 1.9 :: A Spy Among Friends :: Marking/logging as Extras downloads complete (/config/extended/logs/extras/138624)

**Comment by RandomNinjaAtk** [comment]
Should be all that is needed. Honestly sometimes videos fail. You should try manually downloading it with yt-dlp. If you cannot manually download it, then its simply a broken video and there is nothing to be done that I'm aware of...

If you can download it manually, then it's probably worth looking into further...

**Comment by memnos** [comment]
Manually download seems to work:

/tmp# yt-dlp https://www.youtube.com/watch?v=uu0lSZaImIs
[youtube] Extracting URL: https://www.youtube.com/watch?v=uu0lSZaImIs
[youtube] uu0lSZaImIs: Downloading webpage
[youtube] uu0lSZaImIs: Downloading android player API JSON
[info] uu0lSZaImIs: Downloading 1 format(s): 248+251
[dashsegments] Total fragments: 1
[download] Destination: Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lSZaImIs]                                                        .f248.webm
[download] 100% of    9.45MiB in 00:00:00 at 10.37MiB/s
[dashsegments] Total fragments: 1
[download] Destination: Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lSZaImIs]                                                        .f251.webm
[download] 100% of    1.91MiB in 00:00:00 at 9.64MiB/s
[Merger] Merging formats into "Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lS                                                        ZaImIs].webm"
Deleting original file Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lSZaImIs].                                                        f248.webm (pass -k to keep)
Deleting original file Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lSZaImIs].                                                        f251.webm (pass -k to keep)

**Comment by RandomNinjaAtk** [comment]
Thanks for the info, I'll look into it but cannot make any promises....

**Comment by memnos** [comment]
But if i give this command:

/tmp# yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" https://www.youtube.com/watch?

I have this:

v=uu0lSZaImIs
[youtube] Extracting URL: https://www.youtube.com/watch?v=uu0lSZaImIs
[youtube] uu0lSZaImIs: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] uu0lSZaImIs: Downloading android player API JSON
[youtube] uu0lSZaImIs: Downloading iframe API JS
[youtube] uu0lSZaImIs: Downloading player 3cd2d050
[youtube] uu0lSZaImIs: Downloading web player API JSON
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] uu0lSZaImIs: Downloading initial data API JSON
[info] uu0lSZaImIs: Downloading 1 format(s): 137+140
[dashsegments] Total fragments: 4
[download] Destination: Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lSZaImIs].f137.mp4
[download]  25.0% of ~  40.00MiB at   14.09MiB/s ETA 00:02 (frag 1/4)[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (10/10)...
[download] fragment not found; Skipping fragment 2 ...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 3 (10/10)...
[download] fragment not found; Skipping fragment 3 ...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 4 (10/10)...
[download] fragment not found; Skipping fragment 4 ...
[download] 100% of   10.00MiB in 00:00:02 at 3.86MiB/s
[dashsegments] Total fragments: 1
[download] Destination: Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lSZaImIs].f140.m4a
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

**Comment by RandomNinjaAtk** [comment]
Try setting the format to: `bv*+ba/b`

I think that's the default when unspecified, see here: https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior

**Comment by memnos** [comment]
Same 

/tmp# yt-dlp -f "bv*+ba/b" https://www.youtube.com/watch?v=uALPPuJcnGQ

[youtube] Extracting URL: https://www.youtube.com/watch?v=uALPPuJcnGQ
[youtube] uALPPuJcnGQ: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] uALPPuJcnGQ: Downloading android player API JSON
[youtube] uALPPuJcnGQ: Downloading iframe API JS
[youtube] uALPPuJcnGQ: Downloading player 3cd2d050
[youtube] uALPPuJcnGQ: Downloading web player API JSON
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] uALPPuJcnGQ: Downloading initial data API JSON
[info] uALPPuJcnGQ: Downloading 1 format(s): 248+251
[dashsegments] Total fragments: 2
[download] Destination: Django Unchained - Trailer italiano in HD [uALPPuJcnGQ].f248.webm
[download]  50.0% of ~  20.00MiB at    9.54MiB/s ETA 00:01 (frag 1/2)[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (10/10)...
[download] fragment not found; Skipping fragment 2 ...
[download] 100% of   10.00MiB in 00:00:01 at 7.32MiB/s
[dashsegments] Total fragments: 1
[download] Destination: Django Unchained - Trailer italiano in HD [uALPPuJcnGQ].f251.webm
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

**Comment by RandomNinjaAtk** [comment]
You changed urls, try the original URL that worked. The other one just might be a problem with the video...

**Comment by memnos** [comment]
Sorry, my error i tried another trailer.

It seems it can download .webm but not mp4

Are is with that one:

/tmp# yt-dlp -f "bv*+ba/b" https://www.youtube.com/watch?v=uu0lSZaImIs
[youtube] Extracting URL: https://www.youtube.com/watch?v=uu0lSZaImIs
[youtube] uu0lSZaImIs: Downloading webpage
[youtube] uu0lSZaImIs: Downloading android player API JSON
[info] uu0lSZaImIs: Downloading 1 format(s): 248+251
[dashsegments] Total fragments: 1
[download] Destination: Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lSZaImIs].f248.webm
[download] 100% of    9.45MiB in 00:00:00 at 14.80MiB/s
[dashsegments] Total fragments: 1
[download] Destination: Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lSZaImIs].f251.webm
[download] 100% of    1.91MiB in 00:00:00 at 9.65MiB/s
[Merger] Merging formats into "Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lSZaImIs].webm"
Deleting original file Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lSZaImIs].f248.webm (pass -k to keep)
Deleting original file Una spia tra noi ｜ Nuova serie ｜ Trailer [uu0lSZaImIs].f251.webm (pass -k to keep)

**Comment by RandomNinjaAtk** [comment]
I wonder if its just some sort if issue with yt-dlp that is upstream and possibly with recent changes to youtube. I'm just making a guess. Because videos are working in my setup, so if its only 1 video occasionally, just maybe ignore it...? 

Not every video will work because sometimes they become private or are just no longer available and this script has no way of knowing that...

If it is an upstream issue, you could post an issue on yt-dlp project...

**Comment by memnos** [comment]
The strage thing is that all series trailer has the same problem, while movie trailers are downloaded ok as i can see

**Comment by RandomNinjaAtk** [comment]
That is odd, considering the Radarr script and the yt-dlp script is essentially the same....

**Comment by memnos** [comment]
Yes, is what i think too.

**Comment by RandomNinjaAtk** [comment]
I think you maybe corrupted your extended.conf

Because you should see the videoFormat variable before the download executes and your not seeing that....
Line in script: https://github.com/RandomNinjaAtk/arr-scripts/blob/e2dc7de05ab385660d80021bed230b94eb3dfd05/sonarr/Extras.bash#L139C122-L139C161

From your log earlier:
`2023-08-12 08:47:25 :: Extras :: 1.9 :: A Spy Among Friends :: 1 of 1 :: Trailer :: Una spia tra noi | Nuova serie | Trailer (uu0lSZaImIs) :: Downloading (yt-dlp :: )...`

So it should have looked like: 
`2023-08-12 08:47:25 :: Extras :: 1.9 :: A Spy Among Friends :: 1 of 1 :: Trailer :: Una spia tra noi | Nuova serie | Trailer (uu0lSZaImIs) :: Downloading (yt-dlp :: bv*+ba/b)...`

**Comment by memnos** [comment]
Well i think you were right.
I tried to replace my extended.conf file and now it seems to work.

Tnx so much


2023-08-12 14:21:51 :: Extras :: 1.9 :: A Spy Among Friends :: Cookies File Not Found!
2023-08-12 14:21:51 :: Extras :: 1.9 :: A Spy Among Friends :: Searching for "it-IT" extras...
2023-08-12 14:21:51 :: Extras :: 1.9 :: A Spy Among Friends :: 1 Extras Found!
2023-08-12 14:21:51 :: Extras :: 1.9 :: A Spy Among Friends :: 1 of 1 :: Trailer :: Una spia tra noi | Nuova serie | Trailer (uu0lSZaImIs) :: Downloading (yt-dlp :: bv*+ba/b)...
[youtube] Extracting URL: https://www.youtube.com/watch?v=uu0lSZaImIs
[youtube] uu0lSZaImIs: Downloading webpage
[youtube] uu0lSZaImIs: Downloading ios player API JSON
[youtube] uu0lSZaImIs: Downloading android player API JSON
[youtube] uu0lSZaImIs: Downloading m3u8 information
[info] uu0lSZaImIs: Downloading 1 format(s): 248+251
[info] There are no subtitles for the requested languages
[download] Destination: /media/Serie_Tv/A Spy Among Friends/trailers/Una spia tra noi Nuova serie Trailer.f248.webm

[download]   0.0% of    9.45MiB at  842.40KiB/s ETA 00:11
[download]   0.0% of    9.45MiB at    1.15MiB/s ETA 00:08
[download]   0.1% of    9.45MiB at    1.89MiB/s ETA 00:05
[download]   0.2% of    9.45MiB at    2.83MiB/s ETA 00:03
[download]   0.3% of    9.45MiB at    4.07MiB/s ETA 00:02
[download]   0.7% of    9.45MiB at    4.42MiB/s ETA 00:02
[download]   1.3% of    9.45MiB at    5.98MiB/s ETA 00:01
[download]   2.6% of    9.45MiB at    8.80MiB/s ETA 00:01
[download]   5.3% of    9.45MiB at   12.19MiB/s ETA 00:00
[download]  10.6% of    9.45MiB at   12.99MiB/s ETA 00:00
[download]  21.2% of    9.45MiB at   16.79MiB/s ETA 00:00
[download]  42.3% of    9.45MiB at   17.86MiB/s ETA 00:00
[download]  84.7% of    9.45MiB at   18.67MiB/s ETA 00:00
[download] 100.0% of    9.45MiB at   18.89MiB/s ETA 00:00
[download] 100% of    9.45MiB in 00:00:00 at 16.78MiB/s  
[download] Destination: /media/Serie_Tv/A Spy Among Friends/trailers/Una spia tra noi Nuova serie Trailer.f251.webm

[download]   0.1% of    1.91MiB at  720.67KiB/s ETA 00:02
[download]   0.2% of    1.91MiB at    1.02MiB/s ETA 00:01
[download]   0.4% of    1.91MiB at    1.58MiB/s ETA 00:01
[download]   0.8% of    1.91MiB at    2.18MiB/s ETA 00:00
[download]   1.6% of    1.91MiB at    3.49MiB/s ETA 00:00
[download]   3.2% of    1.91MiB at    4.26MiB/s ETA 00:00
[download]   6.5% of    1.91MiB at    6.09MiB/s ETA 00:00
[download]  13.0% of    1.91MiB at    8.76MiB/s ETA 00:00
[download]  26.1% of    1.91MiB at   12.08MiB/s ETA 00:00
[download]  52.3% of    1.91MiB at   13.03MiB/s ETA 00:00
[download] 100.0% of    1.91MiB at   16.62MiB/s ETA 00:00
[download] 100% of    1.91MiB in 00:00:00 at 10.42MiB/s  
[Merger] Merging formats into "/media/Serie_Tv/A Spy Among Friends/trailers/Una spia tra noi Nuova serie Trailer.mkv"
Deleting original file /media/Serie_Tv/A Spy Among Friends/trailers/Una spia tra noi Nuova serie Trailer.f248.webm (pass -k to keep)
Deleting original file /media/Serie_Tv/A Spy Among Friends/trailers/Una spia tra noi Nuova serie Trailer.f251.webm (pass -k to keep)
[EmbedSubtitle] There aren't any subtitles to embed
2023-08-12 14:21:55 :: Extras :: 1.9 :: A Spy Among Friends :: 1 of 1 :: Trailer :: Una spia tra noi | Nuova serie | Trailer (uu0lSZaImIs) :: Compete
2023-08-12 14:21:57 :: Extras :: 1.9 :: A Spy Among Friends :: 1 of 1 :: Trailer :: Una spia tra noi | Nuova serie | Trailer :: Processed with SMA...
2023-08-12 14:21:57 :: Extras :: 1.9 :: A Spy Among Friends :: Marking/logging as Extras downloads complete (/config/extended/logs/extras/138624)

**Comment by RandomNinjaAtk** [comment]
I think, if I have the time, I can build in a check to validate the conf files are not corrupted, and if they are corrupted, alert the user and exit the script.... Should be fairly simple because a corrupted conf will result in none of the variables being set. 

That way, it's more easily detectable going forward...

**Comment by RandomNinjaAtk** [comment]
The recent changes should help detect and properly notify the user  going forward, however, its still a bit untested at this time...

**Comment by memnos** [comment]
Great job
