### ISSUE TITLE
[BUG] - All Arrs - Extended not working for the last week or so

### ISSUE THREAD

**Issue by Glynax** [RandomNinjaAtk/arr-scripts#63]
**Application**
I'm pretty sure it's just son/rad/lid/readarr

**Host platform**
Ubuntu Server

**Script**
Technically all of them

**Script Version**
1.0.15

**Describe the bug**
I've noticed literally none of my enabled scripts have been running and they aren't leaving logs either. For example here's what they all look like when I do docker compose up -d

**To Reproduce**
I don't see any errors it's as if the custom cont and custom services folders just stopped working. I made sure they're the same owner/group and executable, like running scripts_init.bash inside of the container DOES work so I'm not sure why they aren't anymore

**Expected behavior**
Expected things to keep auto starting

**Logs/Screenshots**
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-env-file-init
cont-init: info: /etc/cont-init.d/00-env-file-init exited 0
cont-init: info: running /etc/cont-init.d/00-start-container

----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=1000
PGID=1000
UMASK=002
TZ=America/Detroit
----------------------------------------------------------------------

Executing usermod...
usermod: no changes
Applying permissions to /config
cont-init: info: /etc/cont-init.d/00-start-container exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lidarr (no readiness notification)
s6-rc: info: service legacy-services successfully started
[Info] Bootstrap: Starting Lidarr - /app/bin/Lidarr - Version 1.3.5.3530

**Additional context**

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by RandomNinjaAtk** [comment]
Your problem is likely a misconfiguration on your end.

**Comment by Glynax** [comment]
I'm not sure what to look at or change though, they were all working then presumably something updated and now none of them work

**Comment by RandomNinjaAtk** [comment]
You probably just need to re-read the instructions and double/tripple check everything to make sure it’s correct…

**Comment by Glynax** [comment]
Alright after doing the same steps a few more times it clicked. This ONLY works on linux servers containers. I had just switched to hotio when they of course stopped working. I know it says requirements at the top but I didn't realize this custom folder stuff was unique to them. Back to linux server and they all work.
