### ISSUE TITLE
Skipping previously downloaded trailers - Radarr

### ISSUE THREAD

**Issue by Anqui3tas** [RandomNinjaAtk/arr-scripts#64]
Is there a way it can create or maintain a list of titles it's already downloaded for so it doesn't need to search them again? 

Since this appears to search for the trailer, then realizes it's already downloaded so it's then skipped. 

Or does it do it this way since Radarr has a habit of deleting extras like trailers and posters when upgrading or doing other tasks?

2023/08/25 12:36:46 | stdout | 2023-08-25 12:36:46 :: Extras :: 1.2 :: Fast Five :: 1 of 3 :: Trailer :: Finished processing single trailer download
2023/08/25 12:36:46 | stdout | 2023-08-25 12:36:46 :: Extras :: 1.2 :: Fast Five :: 1 of :: Trailer :: Legacy Trailer (P1UVXvKnCLM) :: Already Downloaded, skipping...
2023/08/25 12:36:46 | stdout | 2023-08-25 12:36:46 :: Extras :: 1.2 :: Fast Five :: 1 of 3 :: Trailer :: Single Trailer Enabled...
2023/08/25 12:36:46 | stdout | 2023-08-25 12:36:46 :: Extras :: 1.2 :: Fast Five :: 3 Extras Found!
2023/08/25 12:36:46 | stdout | 2023-08-25 12:36:46 :: Extras :: 1.2 :: Fast Five :: Searching for "en-US" extras...
2023/08/25 12:36:46 | stdout | 2023-08-25 12:36:46 :: Extras :: 1.2 :: Cookies File Not Found!
2023/08/25 12:36:45 | stdout | 2023-08-25 12:36:45 :: AutoExtras :: 1.5 :: 1097 of 4672 :: 5741 :: Processing with Extras.bash

Also, is a Cookie file needed for trailer downloading? if so, do you have instructions on generating this file?

**Comment by RandomNinjaAtk** [comment]
No response, assuming resolved..
