### ISSUE TITLE
Using this on WSL?

### ISSUE THREAD

**Issue by Yankees4life** [RandomNinjaAtk/arr-scripts#65]
I'm pondering if there's a way to use this on WSL without installing any containers. I got some music videos I want to grab using the lidarr tool but I already installed the windows app for that.

Cheers

**Comment by RandomNinjaAtk** [comment]
These are scripts designed to work with specific containers, but can be easily adapted, just know it’s not directly supported. This is all just bash…. A lot of hours have been put into them though…
