### ISSUE TITLE
Converted Files Not Being Imported To Lidarr

### ISSUE THREAD

**Issue by mbc0** [RandomNinjaAtk/arr-scripts#72]
**Application**
SABnzbd

**Host platform**
Ubuntu

**Script**
audio.bash

**Script Version**
Just downloaded today from github, cannot see version

**Describe the bug**
downloading FLAC and converting to opus 320.  Album downloads fine, I can see the files being converted successfully in the download folder, I can then see the files disappear after encoding and lidarr reports the album in the history tab but only the album title with the track column blank (not normal as usually all tracks are listed)  Files are nowhere to be found and lidarr reports the album as still missing, no errors shown in lidarr.  If I disable the script, files download and import without issue as flac.  If an album downloads and is reported as non-split they also import successfully as flac.

**To Reproduce**
download any flac album in lidarr using SABnzbd script

**Expected behavior**
converted opus files should be imported as individual tracks

**Logs/Screenshots**
https://nextcloud.theroundbox.co.uk/s/SC4rFtXcCrs4Jzz

**Additional context**

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by RandomNinjaAtk** [comment]
If no files are being imported, that would indicate a new import behavior in Lidarr and probably nothing can be fixed....

Technically, Lidarr should be expecting flac files from a flac release, and this kinda usurps that by modifying them to the desired quality... Lidarr used to import them, even if the quality didn't match... But it may no longer do that... And if that is the case, there is nothing that can be done to fix it... Without a change to lidarr....

If I have some time to confirm that, I will and then the transcoding feature will just need to be removed as it is useless...

**Comment by mbc0** [comment]
Thanks for the reply, I appreciate that, I will wait to hear from you to confirm/deny the new lidarr import method before finding an alternate method.
