### ISSUE TITLE
[Feature Request] - Hotio Container Support

### ISSUE THREAD

**Issue by Uplinkpro** [RandomNinjaAtk/arr-scripts#76]
Already use all Moddable Hotio docker containers (all just using themepark) would it be possible to use these scripts on those or add support for it?

**Comment by RandomNinjaAtk** [comment]
I can tell you it's not something I'm going to work on... Unless I have a reason to personally move to using Hotio containers... But I'd welcome a PR that introduces compatibility...

At the end of the day these are just bash scripts, so there isn't too many blockers preventing them from running... it's more a matter of putting time and effort to figure out what changes are needed and resolving issues, that I simply don't have time for when I don't have a personal use...

**Comment by murmelbahn** [comment]
You can use themepark skins with the linuxserver.io containers
