### ISSUE TITLE
[FEATURE] - Radarr and Sonarr - Autoconfig

### ISSUE THREAD

**Issue by PutzJimmy** [RandomNinjaAtk/arr-scripts#81]
Hi. Saw this in the Lidarr extended.conf and this would be so nice in Radarr and Sonarr too =)

##### ATUOCONFIG SCRIPT SETTINGS
configureMediaManagement="true"
configureMetadataConsumerSettings="true"
configureMetadataProviderSettings="true"
configureCustomScripts="true"
configureLidarrUiSettings="true"
configureMetadataProfileSettings="true"
configureTrackNamingSettings="true"

**Comment by RandomNinjaAtk** [comment]
Latest changes, should have this fully implemented, but it is untested... Test and report back...

**Comment by PutzJimmy** [comment]
Awesome as always 👌 Gonna update and test when i get back home 😃

**Comment by PutzJimmy** [comment]
As far as i can tell its working, thx
