### ISSUE TITLE
Lidarr - Downloading Unmonitored Albums

### ISSUE THREAD

**Issue by Simpuhl** [RandomNinjaAtk/arr-scripts#82]
**Application**
Lidarr

**Host platform**
Synology

**Script**
https://github.com/RandomNinjaAtk/arr-scripts/blob/main/lidarr/readme.md

**Script Version**
Latest

**Describe the bug**
Downloading and importing unmonitored albums that are not part of Missing/Cutoff Unmet.

**To Reproduce**
Not sure how-to re-produce exactly and it may be my fault, but I am just letting it do its thing and I keep finding new albums that don't even exist in my library to begin with.

**Expected behavior**
Only download monitored albums in Missing/Cutoff Unmet.

**Logs/Screenshots**
N/A - Can provide if needed but this might just be user error.

**Additional context**
The only thing I am thinking is because I have this:

matchDistance="10"

But my assumption that means 10 track difference? Like if i have a regular album, I'd prefer it to get the deluxe if its available. Let me know if this is the reason so I can just set this to 0.

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by Simpuhl** [comment]
Maybe pull the track listing and look for X amount of tracks comparison from what's in lidarr vs what it found. If it has atleast X same tracks then it can be used.

Bur also maybe add words like remastered, deluxe, extended as preferred if they are part of the title when searching? Idk just talking out of my ass

**Comment by RandomNinjaAtk** [comment]
It already filters by track count.

**Comment by Simpuhl** [comment]
Here some recent logs, I can't find any recent albums as I cleared all the previous albums out so it would retry them all... but I did catch something here:

https://privatebin.net/?ffa4c7f81b10a691#9svFN56SdFu1M9mHeMxj61MoyUEXup5CQpbv6nVXrLZZ

If you look at the album for Akon - Freedom

It download all the tracks successfully, but it never imports it?

I double checked and I still have v0 mp3 and no flacs. I found it interesting so I wanted to share it.

I managed to download the entire album from Deemix (deezer) without any issues and import it manually after I took this screenshot.

https://i.imgur.com/JHMhW9Y.png

**Comment by RandomNinjaAtk** [comment]
The script basically just downloads and tells lidarr a download finish and is ready for import, after that, it is all up Lidarr.... So when something does not import, you have to look at lidarr logs to identify the reason. Lidarr handles the entire import process and there is nothing that can be done on the scripts end...
