### ISSUE TITLE
Adding back ExtendedReleaseAdder to Lidarr extended scripts

### ISSUE THREAD

**Issue by steve1977** [RandomNinjaAtk/arr-scripts#84]
Lidarr extended include the script above. Github: https://github.com/Makario1337/ExtendedReleaseAdder

This could be activtade through setting extra parameters. Could this be done again?

Thanks!

**Comment by RandomNinjaAtk** [comment]
All the packages should be installed that are needed. You'll just need to take the time to integrate and test it... It's not something I used, so I will not work on it, but I'll review a PR for the changes needed and help make tweaks if needed...

**Comment by steve1977** [comment]
It used to work "out of the box" when it was lidarr-extended. Just had to add an extra parameter. Maybe @Makario1337 will have na idea how to "activate it" now. I believe he did the original pull request with lidarr-extended and created the script.

**Comment by steve1977** [comment]
Any reason why you wouldn't add this back? Ideally even linked to @Makario1337 github, so it stays updated if something changes?

**Comment by RandomNinjaAtk** [comment]
You were already provided a solution. Nothing more to do here…
