### ISSUE TITLE
Radarr+Sonarr Scripts - Reverting the quality settings

### ISSUE THREAD

**Issue by Killface1980** [RandomNinjaAtk/arr-scripts#85]
**Application**
Radarr and Sonarr 

**Host platform**
Docker

**Script**
Please identify which script your having a problem with...

**Script Version**
current

**Describe the bug**
Sonarr and Radarr always reset the quality settings to, I guess, the Arr scripts default.
It seems as if mainly the 1080 settings are affected. Every time I reset the values/edit them to my liking, it tales only half a day and everything's set the way it wasn't saved.

**To Reproduce**
1. Revert quality settings to default or save your own
2. Waait for Radarr/Sonarr use different settings

**Expected behavior**
Keeping the quality settings as the user provided.

**Logs/Screenshots**
Radarr
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/16738568/375c4d12-6973-4a8e-9ccc-e48f6345944e)

Sonarr
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/16738568/aef966ce-6fae-4139-a381-c2c93665e292)

**Comment by RandomNinjaAtk** [comment]
If you have recyclarr enabled, that is what is changing it….

**Comment by Killface1980** [comment]
Thank you, I'll take a look what Recyclarr tries to achieve. Otherwise, I'll turn it off for good.

**Comment by Killface1980** [comment]
Update: I've edited the recyclarr.yaml files and removed the quality definitions, as https://recyclarr.dev/wiki/yaml/config-reference/quality-definition/ stated those are optional.

Both Sonarr and Radarr keep re-adding those unwanted settings on restart of the docker container. 
I think I skip Recyclarr entirely, as this is unusable ath the moment and leads to unwanted 20+ GB downloads.

**Comment by RandomNinjaAtk** [comment]
The recyclarr config file should not be getting reset on container restarts. Your customizations to the yaml file should stay intact... Is that not the case?

You can see where it is not to be overwritten:
https://github.com/RandomNinjaAtk/arr-scripts/blob/8b8f3bf844a476cd4b6e82f79c77fb57d16191cf/radarr/setup.bash#L95-L98

https://github.com/RandomNinjaAtk/arr-scripts/blob/8b8f3bf844a476cd4b6e82f79c77fb57d16191cf/sonarr/setup.bash#L100-L104

**Comment by Killface1980** [comment]
Not sure what's happening. The yaml is being partially overwritten. The ip for the server stay intact, same as the API key.
But everytime I modify/delete the lines and restart any of the containers,     ```
    quality_definition:
      type: sqp-streaming
```
or
```
    quality_definition:
      type: series
```
they get re-added.

/EDIT: Realized that this time also the IP address and API keys were overwritten.

**Comment by RandomNinjaAtk** [comment]
If you watch the container startup logs, you should see where it downloads the config files...

If it doesn't say "Download Recyclarr config...", then it isn't updating the file from online, so it shouldn't be overwriting changes. And if it is, then maybe there is a bug somewhere....

**Comment by RandomNinjaAtk** [comment]
Your feedback did identify a problem, it should now be fixed. Apparently when I made it not overwrite the conf, I did some copy/pasta and didn't remove the original download/overwrite. 

So it was always being overwritten. This should now be fixed going forward....

**Comment by Killface1980** [comment]
Thank you very much!
