### ISSUE TITLE
[BUG] - Lidarr - Deleting Torrents when stuck in Queue without MB Mismatch

### ISSUE THREAD

**Issue by Simpuhl** [RandomNinjaAtk/arr-scripts#86]
**Application**
Lidarr

**Host platform**
Synology

**Script**
Lidarr Script

**Script Version**
Latest

**Describe the bug**
If I download an album from a tracker, and it has any mismatches with MB it would normally sit in the queue and wait to be manually imported, however the script is deleting these along with deleting the torrent file.

**To Reproduce**
1. DL album from a tracker that is not in MB

**Expected behavior**
It should ignore anything that is in the normal Lidarr queue

**Logs/Screenshots**
https://github.com/Lidarr/Lidarr/issues/4143

**Additional context**

**NOTE**
Your request will not be addressed without proper detail and logs. Always make sure you have updated to the latest script versions before opening an issue or your issue will not be reviewed.

**Comment by Simpuhl** [comment]
Nm I think I just need to disable the queue cleaner?

**Comment by RandomNinjaAtk** [comment]
> Nm I think I just need to disable the queue cleaner?

Yes...
