### ISSUE TITLE
[FEATURE] - Lidarr - Re-Add possibility to select the container format

### ISSUE THREAD

**Issue by Killface1980** [RandomNinjaAtk/arr-scripts#88]
Lidarr Extended had an option to chose between MKV and MP4 as container format.
Would it be possible to re-add the option?

For proper integration of the videos in my media center, it's essential for me to use MP4 as AudioRanger (a music tagging app) can process MP4 but no MKV. 
I've set up Tdarr to convert the files myself, only to realize that the new Lidarr script marks the videos as missing so I end up with a self-created MP4 and a redownloaded MKV file.

**Comment by RandomNinjaAtk** [comment]
I currently don't have the cycles to work on this and it isn't a feature I use... So a PR is the recommended path forward...

**Comment by RandomNinjaAtk** [comment]
#160
