### ISSUE TITLE
[FEATURE] - Lidarr - Change Freyr cache folder

### ISSUE THREAD

**Issue by patsaindon** [RandomNinjaAtk/arr-scripts#94]
Using Lidarr container, the Freyr cache folder is filling space and needs to be cleared.

A way to change le cache folder path or a n automation to clear would be nice.

**Comment by RandomNinjaAtk** [comment]
Please provide the location of the folder, clearing can be possible, I'm not sure if we'll be able to move it....

**Comment by patsaindon** [comment]
The path is /root/.cache/FreyrCLI/

**Comment by RandomNinjaAtk** [comment]
Update to the latest and see if its fixed.... I have not tested it....

**Comment by patsaindon** [comment]
Seemed to be fixed with latest verdion.

Thank you.
