### ISSUE TITLE
[BUG] -  script_init.bash - Failure Writing

### ISSUE THREAD

**Issue by xZourSx** [RandomNinjaAtk/arr-scripts#95]
**Application**
Radarr

**Host platform**
Synology

**Script**
script_init.bash

**Script Version**
Latest

**Describe the bug**
![image](https://github.com/RandomNinjaAtk/arr-scripts/assets/61470872/bd121b1c-2b04-4650-a572-614de7e7a294)

**To Reproduce**
I have used your process : 
_**Add 2 volumes to your container
/custom-services.d and /custom-cont-init.d (do not map to the same local folder...)
Docker Run Example:
-v /path/to/preferred/local/folder-01:/custom-services.d
-v /path/to/preferred/local/folder-02:/custom-cont-init.d
Download the [script_init.bash](https://github.com/RandomNinjaAtk/arr-scripts/blob/main/radarr/scripts_init.bash) and place it into the following folder: /custom-cont-init.d
Start your container and wait for the application to load
Optional: Customize the configuration by modifying the following file /config/extended.conf
Restart the container**_

**Logs/Screenshots**
Screenshot has been set higher

Thank you for your help

**Comment by xZourSx** [comment]
This version is OK : 
Script_bach : 
#!/usr/bin/with-contenv bash
curl https://raw.githubusercontent.com/RandomNinjaAtk/arr-scripts/main/radarr/setup.bash | bash
exit

Thank you for your feedback

**Comment by RandomNinjaAtk** [comment]
No fix was needed, but I did update the readme's to make it a bit more clear...

**Comment by xZourSx** [comment]
Sorry we may misunderstood ourselves, the script version is indeed good but the issue is still there. 
Can you reopen the ticket or should I create a new one ?

**Comment by RandomNinjaAtk** [comment]
Did you verify the local downloaded script file matches the contents of the one online?

There isn't a fix for this because its a user-error issue. So it's something that went wrong on your end only....

**Comment by githubusr80** [comment]
Post your docker compose or container config here. I think you’re not following the guidlines for the requirements and that is why it isn’t working…. Which again is user-error but your container config would show that…

Also re-read the readme and make sure you’ve met the requirements….

**Comment by xZourSx** [comment]
I've solved the problem.
The file download was not correct, but the content was.
I downloaded the file again and it worked.
